src/starknet.ts
Ran into a problem with `deployContract` where the abi which gets pulled out of the compiled contract json can contain `BigInt`s, which Axios refused to serialize.
An alternative would be to employ Axio's request transformation feature, e.g.: https://itstalwar15.medium.com/handling-bigint-in-axios-using-json-big-in-javascript-d915ae85ffc0
Limitations of this PR:
- No test case, because the work of making a test case would've prevented me from submitting this at all 😅 
- It may be better to [systematically transform axios requests](https://itstalwar15.medium.com/handling-bigint-in-axios-using-json-big-in-javascript-d915ae85ffc0)
=> fix: protect bigints in axios payloads

__tests__/utils/utils.test.ts, src/utils/stark.ts
Implements https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/hash_chain.py in JS which is a very common function to use. 
It'll also be used by wallet implementations in the future.
=> feat: add computeHashOnElements

src/constants.ts, src/contract.ts, src/types.ts
Currently, starknet.js doesn't do a good job with structs, such as the Uint256 struct returned by the ERC20 contract. Instead of returning all the fields of the struct, it just returns the first field.
Concretely, if a user had a balance of 1 in an ERC20 contract, this is what would have been returned from `balance_of` previously:
```json
{ "res": "0x0" }
```
With this change we properly parse the Uint256 struct, so the method will instead return the following:
```json
{ "res": { "low": "0x1", "high": "0x0" } }
```
=> fix: correctly parse structs in Starknet return types

__tests__/utils/shortString.test.ts, __tests__/utils/uint256.test.ts, src/constants.ts, src/index.ts, src/utils/shortString.ts, src/utils/stark.ts, src/utils/uint256.ts
This PR implements utils to handle Cairo short strings and Cairo uint256 structs
=> feat(utils): support shortstring and uint256

src/contract.ts
Add an option to pass block identifier to contract calls.
For example: sometimes we would like to query the calls for the most updated state (i.e, on the pending block).
`contract.call('balanceOf', {account}, "pending")`
=> feat(Contract): add an option to pass block identifier to call API

__tests__/account.test.ts, src/account/default.ts, src/account/interface.ts, src/contract.ts, src/provider/interface.ts, src/signer/default.ts, src/signer/interface.ts, src/types/api.ts, src/types/lib.ts, src/types/signer.ts
This PR aims to support batch transactions natively. 
To archive this it's necessary to introduce a new method and not further inherit the interface of `invokeFunction` which is designed to always match the sequencers api, which in any case accepts one call only.
=> feat(account): introduce execute method

src/provider/default.ts
To enable backwards compatibility of starknet.js v2
=> feat(provider): add back legacy `invokeFunction`

src/account/default.ts, src/contract/default.ts, src/contract/interface.ts, src/provider/default.ts, src/provider/utils.ts, src/types/api.ts
After speaking to starkware it turned out "PENDING" should already be used as a done state.
To reflect that in calls we need to query the pending block by default.
=> feat: pending as success

README.md, __tests__/jest.setup.ts, package-lock.json, package.json, src/provider/default.ts
axios (which uses the `XMLHttpRequest` interface) isn't supported in service workers.
instead, we can use `cross-fetch` which supports single js code for node, browser and react-native
=> fix: allow starknet.js in service workers

__tests__/provider.test.ts, src/account/default.ts, src/constants.ts, src/provider/default.ts, src/types/api.ts, src/types/lib.ts, www/docs/API/provider.md
This PR introduces support for the new 'declare' workflow introduced at Starknet's latest 0.9.0 upgrade.
[Starknet docs](https://docs.starknet.io/docs/Blocks/transactions/#declare-transaction)
=> feat: support contract declaration API introduced at SN 0.9.0

package-lock.json, package.json, src/provider/index.ts, src/provider/utils.ts
This fixes a problem with the re-throwing of GatewayError, which doesn't work as expected.
Extending the native Error object causes surprising unintended results when using Babel / Typescript. for example `err instanceof GatewayError` is always false.
for more information see https://github.com/adriengibrat/ts-custom-error#why
Ragarding the existing test coverage - the test environment uses a different transpiler config and runs in node, so the tests pass but the code fails in the built version.
=> fix(GatewayError): use ts-custom-error to support

www/docs/API/account.md
The structor of Account is:
src/account/default.ts:32
```
export class Account extends Provider implements AccountInterface {
public address: string;
...
```
The address of Account should be get by `Account.address`, instead of `Contract.address`.
=> fix(docs): account.address

src/account/default.ts, src/types/account.ts, src/types/api.ts
estimate_fee response was changed. namely 'amount'->'overall_fee'
Added support in a backward-compatible manner per @janek26 suggestion
=> feat: support SN 0.9.1 estimate_fee response

__mocks__/typedDataStructArrayExample.json, __tests__/utils/typedData.test.ts, src/utils/typedData/index.ts
Fixes https://github.com/0xs34n/starknet.js/issues/260 as well as generation of the type hash with struct array dependencies.
Hashes an array of structs like so:
```
// struct s
a = [s1, s2, ..., sn]
// hash each struct individually to get a list of hashes(felts)
[H(s1), H(s2), ..., H(sn)]
// hash list of felts as per usual (computeHashOnElements in starknet.js)
H(a) = H(...H(H(H(s1), H(s2)), H(s3)), ..., H(sn))
```
=> Struct array hashing

src/provider/default.ts
Issue: 
Following error on `node` env in `v3.17.0`:
`fetch is not defined`
Solution: 
We should use the `fetch` function of `cross-fetch` (i.e. `import fetch from 'cross-fetch'`) instead of using the global fetch (on browsers `window.fetch`, on node `this.fetch`).
=> fix: 'fetch is not defined' on node dev

www/docs/API/provider.md
A typo in the description of the waitForTransaction() method was preventing the method name from appearing in bold.
=> Correct minor error in documentation

__tests__/defaultProvider.test.ts, package-lock.json, package.json, src/provider/default.ts, src/provider/interface.ts, src/provider/rpc.ts, src/provider/sequencer.ts, src/types/api/sequencer.ts, src/types/provider.ts, src/utils/responseParser/rpc.ts, src/utils/responseParser/sequencer.ts
adds the currently supported `getCode` endpoint for rpc and sequencer
In the future this will be replaced by contract class calls, but that's not supported right now while get_code is supported by sequencer and rpc
=> feat: get-code

__tests__/sequencerProvider.test.ts, src/index.ts, src/provider/sequencer.ts, src/utils/url.ts, www/docs/API/provider.md
Currently, the way feederGatewayUrl and gatewayUrl that are being assigned value is wrong.
```
this.feederGatewayUrl =
optionsOrProvider.feederGatewayUrl ?? urljoin(this.baseUrl, 'feeder_gateway');
```
This won't work if `feederGatewayUrl='feeder_gateway'` as described in the [docs](https://www.starknetjs.com/docs/api/provider/#creating-an-instance)
It will fail with the following error when making contract calls:
```Error: Could not POST from endpoint `feeder_gateway/call_contract?blockNumber=pending`: Only absolute URLs are supported``` 
This PR aims to fix this bug by taking into account that feederGatewayUrl can be a url. for eg: `https://alpha4.starknet.io/feeder_gateway` or just a path which can be concatenated with baseUrl.. for eg: `feeder_gateway`
=> fix(sequenceProvider): feederGatewayUrl and gatewayUrl

src/provider/rpc.ts, src/provider/utils.ts, src/types/api/rpc.ts
with the recent [update of pathfinder](https://github.com/eqlabs/pathfinder/releases/tag/v0.3.0-alpha), some methods have been deleted, making starknet.js not working when trying to use them
e.g. `starknet_getBlockByHash` and `starknet_getBlockByNumber`, that are used in getBlock method of starknet.js RpcProvider Class
here is an update using new pathfinder `starknet_getBlockWithTxHashes` method instead of these ones
=> fix(RpcProvider): update of RpcProvider methods to work with v0.3.0 of pathfinder

.gitignore, __tests__/defaultProvider.test.ts, __tests__/rpcProvider.test.ts, __tests__/sequencerProvider.test.ts, src/provider/default.ts, src/provider/interface.ts, src/provider/rpc.ts, src/provider/sequencer.ts, src/provider/utils.ts, src/types/api/openrpc.ts, src/types/api/rpc.ts, src/types/provider.ts, src/utils/ellipticCurve.ts, src/utils/responseParser/rpc.ts, src/utils/responseParser/sequencer.ts, www/docs/API/account.md, www/docs/API/provider.md
Fix breaking Tests and open release pipeline
0.1.0
RPC Fixes related to:
- getBlock
- getCode removed
- getStorageAt
- getClassAt
RPC Provider has:
- getBlockWithTxHashes
- getBlockWithTxs
- getTransactionByHash
- getTransactionByBlockIdAndIndex
getClassAt now has 2 parameters for RPC also same as sequencer (contractAddress, blockIdentifier)
openrpc.ts specify mapping of open RPC spec to TS types (work in progress)
=> Rpc 0.1.0 incomplete - only test pass

__tests__/rpcProvider.test.ts, src/provider/rpc.ts, src/utils/number.ts, www/docs/API/utils.md
Co-authored-by: dkillen <david@davidkillen.net>
The StarkNet OpenRPC API spec defines a FELT as a "...field element. Represented as up to 63 hex digits and leading 4 bits zeroed." The RPC write api defines three methods which take an array of FELT as calldata. The RpcProvider has three methods which incorrectly converts an array of BigNumbersih values into a decimal string array rather than an hexadecimal string array to pass as call data. Those methods are:
getEstimateFee()
deployContract()
invokeFunction()
This is the cause of the error described in issue https://github.com/0xs34n/starknet.js/issues/285
Adds new utility method bigNumberishArrayToHexadecimalStringArray() in utils/number.ts to return an hexadecimal string array from an array of BigNumberish values
Replaces the use of …
=> fix: supply calldata as hexadecimal string array

src/account/default.ts, src/provider/default.ts, src/provider/interface.ts, src/provider/sequencer.ts
fix https://github.com/0xs34n/starknet.js/issues/284
1. Issue resolved
RPC constructor retrieves chainId by the async call so calling account estimateFee & execute imediatly after creation could result in failed signerDetails
2. Issue not resolved
This does not resolve issue when you use **provider.chainId** imediatly after construction:
```
console.log('RpcProvider')
const provider = new RpcProvider({
nodeUrl: 'https://starknet-goerli.infura.io/v3/...',
})
console.log(`chainId: ${provider.chainId}`); // undefined
```
- One solution is RPC provider constructor return IIF promise and called with
```
let provider = await new RpcProvider({...})
```
- Second would be to use setter and getter, where getter return promise but both are loosely typed with as 'any'. This would require the …
=> fix: prevent undefined rpc chainId in account

src/provider/rpc.ts
Fix block id on RPC methods getEstimateFee and callContract
Wait for the transaction retry 200 times instead of 100
0.1.0
=> fix: estimateFee and call block id

.github/workflows/release.yml
Fixes the release pipeline needed with starknet 0.10 update. Uses new devnet image.
=> fix(ci): use correct devnet image for release pipeline

CONTRIBUTING.md, __tests__/utils/merkle.test.ts, __tests__/utils/typedData.test.ts, src/utils/merkle.ts
Merkle tree generation was relying on a sorted pedersen hash function (as described in #341 ). The sorting function was doing a string compare which can easily fail when comparing to hex strings. For example: `'0xa' > '0x12' = true` when of course `10 > 18 = false`. Given that the vast majority of (all?) on-chain Merkle tree verifiers also sort this causes mismatching roots and proofs with higher and higher likelihood the larger the number of leaves.
This change simply casts the hex strings to BN to compare.
N/A
No usage / API changes.
No development related changes.
=> fix: fixed hash arg sorting in merkle tree generation

src/utils/responseParser/sequencer.ts
Fix [296](https://github.com/0xs34n/starknet.js/issues/296) GetTransactionReceiptResponse
Removed non-existing properties
- (+) Remove type error for conditional props, still hint common props
- (+) Now all providers have all props received from this endpoint (before some were missing like block_hash and block_number)
- (-) Allow none existing props by ts
=> fix: issue 296 GetTransactionReceiptResponse

.github/workflows/pr.yml, .github/workflows/release.yml, __mocks__/l1l2_compiled.json, __tests__/fixtures.ts, __tests__/sequencerProvider.test.ts, src/provider/sequencer.ts, src/types/api/sequencer.ts, src/utils/hash.ts, src/utils/number.ts
Fix https://github.com/0xs34n/starknet.js/issues/339
Provide a new function for estimating L1 -> L2 message fee
New workflow devnet with implementation - tag release
```ts
type CallL1Handler = {
from_address: string; // L1 Address
to_address: string; // L2 Address
entry_point_selector: string; // L2 Cairo function with @l1_handler
payload: Array<string>; // L2 Cairo function params
};
```
```js
sequencerProvider.estimateMessageFee(CallL1Handler [, blockIdentifier])
```
Despite data type inconsistency between estimate fee and estimate message fee,
estimateMessageFee is implemented so that users can pass a decimal string or Hex String and for entry_point_selector decimal string, hex String, or function name and it will be formatted as endpoint required.
**Extended Utils and Numbers** with …
=> Sequencer estimate message fee

__tests__/utils/merkle.test.ts, __tests__/utils/typedData.test.ts, src/utils/merkle.ts
This issue was not properly corrected in previous attempt (see https://github.com/0xs34n/starknet.js/pull/331 now closed). The goal of this new PR is to have a merkle proof that is fixed in size and matches the depth of the tree. It would also have to be correct!
1. SessionKey.cairo in the contract project, shows 3 things:
- the proof verification does not treat 0x0 in any specific ways. It would simply be applied
- it does not rebuild the root but just compare it with the proof
- the length of the proof has to be the same for all the calls in the multicall
2. The first step of this PR consists in producing some failing tests, A good one is actually the one with 7 values where we pick 0x5 to start. It shows that:
```
Array [
"0x6",
- …
```
=> fix issue with fix-size merkle tree

__tests__/account.test.ts, src/account/default.ts
Solves #391 
Estimate fee calls should use `feeTransactionVersion`
- [ X] Performed a self-review of the code
- [ X] Rebased to the last commit of the target branch (or merged it into my branch)
- [ X] Linked the issues which this PR resolves
- [ X] Updated the tests
- [ X] All tests are passing
=> fix: change txn version for estimate fee apis to be feeTransactionVersion

src/provider/default.ts, src/provider/interface.ts, src/provider/rpc.ts, src/provider/sequencer.ts
Deprecate all providers deployContract in preparation to removal
=> fix: anotate deprecate all providers deployContract

src/contract/default.ts
When I try to pass BlockIdentifier 'latest' to contract call, Starknet.js still uses 'pending'
n/a
- When users want to fetch data from 'latest' block, Starknet.js will properly use 'latest' BlockIdentifier.
n/a
https://github.com/0xs34n/starknet.js/issues/419
=> fix: properly parse blockIdentifier in buildCall function

__tests__/account.test.ts, __tests__/contract.test.ts, __tests__/defaultProvider.test.ts, __tests__/fixtures.ts, __tests__/rpcProvider.test.ts, __tests__/sequencerProvider.test.ts, __tests__/utils/utils.test.ts, package.json, src/account/default.ts, src/account/interface.ts, src/contract/contractFactory.ts, src/provider/default.ts, src/provider/interface.ts, src/provider/rpc.ts, src/provider/sequencer.ts, src/types/account.ts, src/types/lib.ts, src/types/provider.ts, src/utils/events.ts, src/utils/number.ts, www/docs/API/account.md, www/docs/API/contractFactory.md, www/docs/API/provider.md, www/docs/API/utils.md, www/guides/account.md, www/guides/erc20.md
**Starknet alpha v0.10.3**
Provider.deployContract removal, deploy need to be done true Account
**Account.deploy** -> low level deploy contract, return transaction_hash
NEW **Account.deployContract**  -> high-level deploy (doesn't require waitForTransaction)
- required params: `classHash`
- return: `same data as provider.deployContract + UDC specific data`
NEW **Account.declareDeploy** -> high-level  declare & deploy (doesn't require waitForTransaction)
- required params: `same as provider.deployContract + classHash`
- return: 
```js
{
declare: TransactionReceiptResponse,
deploy: "same data as provider.deployContract + UDC specific data"
}
```
Open Questions:
Should Account.deployContract & Account.declareDeploy be part of Account or contractFactory?
0.2.1
Switch to Account.deploy or …
=> [Stage 1] Starknet alpha v0.10.3 - account deployContract, test, refactor

package-lock.json, package.json
Fix https://github.com/0xs34n/starknet.js/issues/372
=> chore: bump ts-custom-error

src/provider/sequencer.ts
Fix https://github.com/0xs34n/starknet.js/issues/401
No breaking changes just extends existing functionality
Enable usage of ChainId in network parameter when creating a new Sequencer provider.
`new Provider({ sequencer: { network: "mainnet-alpha" | "goerli-alpha" | "goerli-alpha-2" } })`
Now you can do also
`new Provider({ sequencer: { network: "0x534e5f4d41494e" | "0x534e5f474f45524c49" | "0x534e5f474f45524c4932" } })`
Or
`new Provider({ sequencer: { network: StarknetChainId.MAINNET | StarknetChainId.TESTNET | StarknetChainId.TESTNET2 } })`
=> feat: allow usage of chainId to define network, cleanup

__tests__/account.test.ts
Hi again, 
I created a fix considering [this](https://github.com/0xs34n/starknet.js/actions/runs/3624531902/jobs/6111618765) problem on testnet-2 testing. 
I hard-coded the signature cause I thought tests were only run locally, and of course as the account.address was different during testnet-2 tests so the signatures were also different. 
My bad. 
Now it works cause I'm recreating the signature myself with the account.address as an argument.
=> fix: add testnet 2 compatibility to test

__tests__/account.test.ts, src/account/default.ts, src/account/interface.ts, src/types/account.ts, src/types/lib.ts, www/docs/API/account.md
Fix https://github.com/0xs34n/starknet.js/issues/442
add the precalculated address on the deploy return.
added support for multi-deploy with singular payload. We had it before but the user would need to open the source code copy function body and basically create a call by himself and pass that to the additional parameter.
=> feat: return precalculated address from deploy, reimplement multi-deploy

package.json
This addresses an issue reported through Telegram where a bundling process using `browserify` internally is running into issues by attempting to rebundle the `iife` build. Normally it wouldn't make sense to address the issue in this module, however, this change should both resolve that issue and maintain the relevant functionality.
=> build: make the CDN entry points more explicit

src/account/default.ts, src/account/interface.ts, src/provider/rpc.ts, src/types/api/openrpc.ts
RPC deployAccountContract has misformatted request data.
~~RPC nonce for non-existing account return error and sequencer return "0x0" which cause a problem when deploying account true RPC.~~
Fixture deploy Account nonce to 0
Fixture estimateAccountDeployFee nonce to 0
0.2.1
RPC deployAccount fixed
~~Include hotfix for RPC-spec deviation (but this will be discussed for standardization)~~
=> fix: rpc deployAccountContract request, rpc nonce hotfix

src/provider/rpc.ts
`RpcProvider.invokeFunction` throws an error complaining `unknown field 'sender_address'` because its request payload follows V1 but version is set V0. Actually, it is correctly written as 1 in `SequencerProvider`.
Invoke Tx will be successfully broadcasted even though user don't specify `version` explicitly.
=> RpcProvider: Fix default invoke tx version

www/guides/erc20.md, www/guides/multiCall.md
When I was checking the Erc20 token guide in doc, I found an error in sample code. 
- In cairo language, the uint256 contains two felts, in js, the first element of the array is low 128 bits, the second element of the array is high 128 bits. Sample in docs is transfering way more than 10 tokens.
- Using compileCalldata for `uint256` will add an element of array length to the `uint256 array`, which will cause error when passing args. Treating `uint256` stuff as a struct solves the problem.
- When I want to check how to interact more than one contract within one transaction, there is no refer in the doc. After I worked it out, I'm trying to add it to the doc for others to check.
- Change 1.
Modify errors in erc20.md.
- Change 2.
Add multiCall sample code to the guide section in …
=> Modified errors in erc20.md and add file multiCall.md

__tests__/sequencerProvider.test.ts, src/provider/sequencer.ts, src/types/api/sequencer.ts, www/docs/API/Provider/sequencerProvider.md
Close #253 
Add support for `get_block_traces` endpoint in Sequencer Provider.
=> Feat: support get_block_traces in sequencer provider

www/docs/API/account.md
Fixed the description of the `transactions` variable data type in the `execute` section, and added the `execute` code example
=> modify account.md

__tests__/utils/shortString.test.ts, src/utils/encode.ts
Fix https://github.com/0xs34n/starknet.js/pull/508
Mentioned PR contains change so that call on function decodeShortString can handle both hex and decimal string, usage-related change.
```decodeShortString(value.toString(16)) -> decodeShortString(value)```
But removeHexPrefix removes only `0x` and not `0X`. That produces a hidden character on the string that encodes, visible with JSON.stringify.
The issue is that removeHexPrefix should be able to remove both, not just in the mentioned PR but in case someone does an uppercase transformation before the call.
...
...
removeHexPrefix is case insensitive `0x` and `0X`
=> fix: remove hex prefix should work insensitive, for both 0x and 0X

README.md, www/docs/API/Provider/provider.md, www/docs/API/contract.md, www/docs/API/contractFactory.md, www/docs/API/index.md, www/docs/API/signer.md, www/docs/API/utils.md, www/docs/guides/L1message.md, www/docs/guides/create_account.md, www/docs/guides/create_contract.md, www/docs/guides/estimate_fees.md, www/docs/guides/events.md, www/docs/guides/intro.md, www/docs/guides/multiCall.md, www/docs/guides/use_ERC20.md, www/docs/guides/what_s_starknet.js.md
Changes the spelling of "StarkNet" from "StarkNet" to "Starknet" everywhere in the doc following the recommendations in [this SNIP](https://community.starknet.io/t/snip-naming-convention-starknet-not-starknet).
=> Change "StarkNet" to "Starknet"

__tests__/utils/starknetId.test.ts, src/utils/starknetId.ts
Just noticed that the testnet address contract is the old one. I just changed it with the right one.
They will retrieve the current testnet contract and not the old one.
=> fix: add new starknet id contracts (testnet)

src/provider/sequencer.ts, src/types/api/sequencer.ts
Adding `max_fee` to `getSimulateTransaction`. I don't know why it is not present, I assume it's a bug and this is the fix.
It is required to get the trace of a  transaction before submitting it. 
Waiting for sequencer v0.11 to skip validation is also not a viable solution as one might need validation to be performed. (and the transaction hash to be correct). Or worse doing another signature without the max_fee field
- No more  ```Signature (xx, xx), is invalid, with respect to the public key xx, and the message hash xx.``` when using `simulate_transaction`
=> fix: add max_fee to sequencer getSimulateTransaction

src/utils/hash.ts, src/utils/num.ts
Solve #554 
`ethereum-cryptography` lib is still used, for the following functions : `keccak256` and `hexToBytes`.
These functions are also available in `micro-starknet` and `noble/curves`.
No changes for users.
`ethereum-cryptography` lib removed.
`num.hexToBytes` has been created ; it verifies and adapt the input, prior to send to noble lib. It avoids possible failures of noble lib.
(for information, reverse function exists already in `encode.buf2hex`).
=> Remove ethereum cryptography v5.2.0

__tests__/account.test.ts, src/account/default.ts, src/contract/default.ts, src/types/contract.ts, src/types/lib/index.ts, src/utils/responseParser/sequencer.ts, src/utils/stark.ts
Fix TS issue with contract.call response
Signature https://github.com/0xs34n/starknet.js/discussions/565
Type-defined but more flexible Signature:
If used as string[] it can be any implementation and default implementation use WeierstrassSignatureType 
No interface changes just redefined types
```ts
export type WeierstrassSignatureType = weierstrass.SignatureType;
export type ArraySignatureType = string[];
export type AnySignatureType = string | number | ArraySignatureType | WeierstrassSignatureType;
export type Signature = ArraySignatureType | WeierstrassSignatureType;
```
=> chore: fix call response type & Signature type

package-lock.json, package.json, src/provider/errors.ts
Due to the bundling issue, reimplemented custom-ts-errors locally.
Please test for chrome ext. @dhruvkelawala, on node imp., this works fine.
=> fix: implement custom ts error localy

__tests__/contract.test.ts, src/contract/default.ts
Solve #632 
Add RawArgsObject type to Account.populate
Users can now use both :
```typescript
const calldata6: Call = myTestContract.populate("test_multi1", [
200, 
234567897n, 
"865423"]);
const calldata7: Call = myTestContract.populate("test_multi1", {
p1: 200, 
p2: 234567897n, 
p3: "865423"});
```
Unordered object is accepted.
No
=> feat: add RawArgs in Account.populate

__tests__/cairo1.test.ts, __tests__/contract.test.ts, src/contract/default.ts, src/contract/interface.ts, src/utils/calldata/cairo.ts, www/docs/guides/define_call_message.md
The way to construct the calldata, and the way to read the answer of a contract function, are not the same for Cairo 0 and Cairo 1.
That's why it's useful to have a method to have the origin of a Contract object, or of an abi variable.
Users have now : 
```typescript
import { cairo } from "starknet";
const isCairo1: boolean = myContract.isCairo1();
const isAbiCairo1: boolean = cairo.isCairo1abi(myAbi);
```
function `isCairo1abi` added in `utils/calldata/cairo/`.
=> feat: isCairo1?

__mocks__/cairo/helloSierra/hello.cairo, __tests__/account.test.ts, __tests__/cairo1.test.ts, src/index.ts, src/provider/rpc.ts, src/types/lib/contract/index.ts, src/types/lib/contract/sierra.ts, src/types/provider/response.ts, src/utils/contract.ts, src/utils/provider.ts
Fix https://github.com/0xs34n/starknet.js/issues/588
Because of cairo0 back compatibility, we left formatting to be compressed program in response class, so it needs to be decompressed for declare and also typecast to legacy.
An example of redeclare cairo0 without a helper will be:
Redeclare cairo0 contract helper:
``contractClassResponseToLegacyCompiledContract();``
Example Cairo0 redeclare:
https://github.com/0xs34n/starknet.js/blob/a5b628fb0248a5c8caddc985cf93b6d53a69bf04/__tests__/account.test.ts#L75
Example Cairo1 redeclare:
https://github.com/0xs34n/starknet.js/blob/a5b628fb0248a5c8caddc985cf93b6d53a69bf04/__tests__/cairo1.test.ts#L60
- Fix ContractClassResponse type
- Extend isSierra() response type to help TS evaluate the resulting type
- [export utils: provider, selector, …
=> 0.11.2/redeclare ts

www/docs/guides/L1message.md, www/docs/guides/connect_account.md, www/docs/guides/connect_contract.md, www/docs/guides/connect_network.md, www/docs/guides/create_account.md, www/docs/guides/create_contract.md, www/docs/guides/define_call_message.md, www/docs/guides/estimate_fees.md, www/docs/guides/events.md, www/docs/guides/interact.md, www/docs/guides/intro.md, www/docs/guides/multiCall.md, www/docs/guides/signature.md, www/docs/guides/use_ERC20.md, www/docs/guides/what_s_starknet.js.md
Docs clarification about https://github.com/0xs34n/starknet.js/issues/674 
..`Sending sequential transactions` in interact.md
=> docs: added waitForTransaction section and cleanups

src/types/provider/response.ts
Added missing transaction_failure_reason as an optional prop on transaction response for Rejected Transactions.
=> Fix FailedTransactionResponse

__tests__/cairo1v2.test.ts, src/contract/default.ts, src/types/contract.ts, src/types/lib/index.ts, src/utils/calldata/index.ts, www/docs/guides/define_call_message.md, www/docs/guides/use_ERC20.md
Solve issue #684 
Contract meta-class now accepts as input the result of the following functions :
- `myContract.populate().calldata`
- `myCallData.compile()`
- `Calldata.compile()`
This code now works for all cases, including u256 :
```typescript
const functionParameters: RawArgsObject = {
val1: 1,
amount: cairo.uint256(15),
}
const myCall0: Call = myTestContract.populate("test9", functionParameters);
const res17 = await myTestContract.test9(myCall0.calldata);
const contractCallData: CallData = new CallData(compiledTest.abi);
const myCalldata: Calldata = contractCallData.compile("test9", functionParameters);
const res19 = await myTestContract.test9(myCalldata);
const contractCallData2: Calldata = CallData.compile(functionParameters);
const res20 = await …
```
=> feat: Calldata result can be used as input in Contract meta-class

__tests__/account.test.ts, __tests__/schemas/rpc.json, src/account/default.ts, src/constants.ts, src/provider/rpc.ts, src/provider/sequencer.ts, src/types/api/openrpc.ts, src/types/api/rpc.ts, src/types/api/sequencer.ts, src/types/lib/index.ts, src/types/provider/response.ts, src/utils/encode.ts, src/utils/responseParser/sequencer.ts
starknet 0.12.1 changes
Sequencer waitForTransaction options:
```ts
type waitForTransactionOptions = {
retryInterval?: number;
successStates?: Array<TransactionFinalityStatus | TransactionExecutionStatus>;
errorStates?: Array<TransactionFinalityStatus | TransactionExecutionStatus>;
};
```
=> feat: 0.12.1

__tests__/contract.test.ts, src/utils/calldata/index.ts
Solve #700 
CallData.compile can now handle a mix of litterals and complex inputs.
A test added to test this specific case
=> fix: calldata.compile ordering problem

__tests__/cairo1_typed.test.ts, www/docs/guides/automatic_cairo_ABI_parsing.md
Add Abi-Wan-Kanabi usage example in the doc guides
=> docs: added abi-wan integration usage example

src/provider/rpc.ts, src/utils/encode.ts
Several people have reported a frozen code at `provider.waitForTransaction()` (see issue #730 for example).
I made many tests with v5,17.0, v5.19.2, Testnet 1, Tesnet 2, Pathfinder rpc 0.4.0, Infura, Alchemy
The problem is with Infura, whatever Starknet.js version and network.
After investigation, I discovered that Infura just bumped to rpc 0.4.0, with full respect of the specification concerning Status (in Upper Case).
So,
- Starknet.js v5.17.0 is not able to handle rpc 0.4.0
- Starknet.js v5.19.2 is not able to handle status in UpperCase (due to the fact that Pathfinder is in lowerCase, and a fix has been implemented in Starknet.js)
Now, Starknet.js will be compatible with a strict respect of rpc 0.4.0 (UpperCase status), and with Pathfinder "nearly" respect of rpc 0.4.0  (lowerCase …
=> fix: waitForTransaction for Infura

__tests__/cairo1v2.test.ts, src/utils/calldata/propertyOrder.ts
One small bug when using a Bignumberish to represent a u256 in myContract.populate or myCallData.compile : the code fails.
The test for u256 has to be made before the test of struct. Just changed the order of the tests.
To reproduce :
```typescript
const myCall = cairo1Contract.populate('test_u256', { p1: 15 });
```
Behavior conform to documentation.
This case was not tested. Test added
=> fix: use BigNumberish for u256 in .populate & myCallData.compile

www/docs/guides/connect_account.md, www/docs/guides/create_account.md, www/docs/guides/create_contract.md, www/docs/guides/interact.md
Solve #686 .
First accounts coded with Cairo v2 language are now arriving in Starknet. It's time to alert that the creation of a such Account object needs a specific optional parameter :
A "1" string has to be added as last parameter  :
```typescript
const OZaccount = new Account(provider, OZcontractAddress, privateKey, "1");
```
The documentation has been updated to alert about this subject.
The community has already been alerted on Discord : [Discord message]( https://discord.com/channels/793094838509764618/927918707613786162/1145015291944906824)
N/A
N/A
=> docs: accounts coded with cairo v2

__tests__/cairo1.test.ts, __tests__/cairo1v2.test.ts, __tests__/contract.test.ts, __tests__/defaultProvider.test.ts, src/account/default.ts, src/contract/default.ts, src/contract/interface.ts, src/provider/default.ts, src/provider/interface.ts, src/provider/rpc.ts, src/provider/sequencer.ts, src/types/lib/index.ts, src/utils/calldata/cairo.ts
Account cairoVersion default ~~0~~ -> undefined
Default cairoVersion will be undefined and Account will 'auto-detect' and set it on the first request.
This is backward compatible and less prone to bugs due to an incorrect Cairo version on the account.
The drawback is only one API Call for the first time setting it.
If the Cairo version is explicitly defined by the user, there are no changes.
New methods:
Account ``getCairoVersion()`` - return Cairo version for the Account
Account ``getCairoVersion(classHash)`` - return Cairo version for the Account by classHash
Provider ``getContractVersion(contractAddress)``- return Cairo and compiler version
Provider ``getContractVersion(undefined, classHash)``- return Cairo and compiler version by classHash
Contract ``getVersion()`` - return Contract's …
=> feat: ContractVersion

package-lock.json, package.json, src/contract/default.ts, src/contract/interface.ts
...
https://github.com/starknet-io/starknet.js/issues/786
...
Only import types from abi-wan and use type import
- Change 1.
- ...
Move abi-wan to dev dependencies and only type import
=> [786]: abi-wan-kanabi moved to devDeps and only type import

src/types/api/rpcspec/components.ts, src/types/lib/contract/legacy.ts, src/types/lib/contract/sierra.ts
Solve issue #797 
PR following https://github.com/starknet-io/starknet.js/issues/797#issuecomment-1785481143
N/A
- Pythonic_hints becomes optional.
- The Casm file accepts entrypoints.offset as number type
=> Fix CairoType type

www/docs/guides/L1message.md, www/docs/guides/connect_account.md, www/docs/guides/connect_network.md, www/docs/guides/create_account.md, www/docs/guides/intro.md, www/docs/guides/signature.md, www/docs/guides/what_s_starknet.js.md, www/versioned_docs/version-4.17.1/guides/intro.md, www/versioned_docs/version-4.22.0/guides/intro.md, www/versioned_docs/version-5.14.1/guides/intro.md, www/versioned_docs/version-5.19.5/guides/L1message.md, www/versioned_docs/version-5.19.5/guides/connect_account.md, www/versioned_docs/version-5.19.5/guides/connect_network.md, www/versioned_docs/version-5.19.5/guides/create_account.md, www/versioned_docs/version-5.19.5/guides/interact.md, www/versioned_docs/version-5.19.5/guides/intro.md, www/versioned_docs/version-5.19.5/guides/migrate.md, www/versioned_docs/version-5.19.5/guides/signature.md, www/versioned_docs/version-5.19.5/guides/what_s_starknet.js.md
In a certain code submission, the `0xs34n` field in the link path of the docs was mistakenly replaced with `starknet-io`, but  the repo does not exist in the `starknet-io`.
...
=> docs: Update broken links in intro docs.

__tests__/fixtures.ts, __tests__/jestGlobalSetup.ts, src/constants.ts, src/provider/default.ts, src/provider/rpc.ts, src/types/provider/configuration.ts
fix https://github.com/starknet-io/starknet.js/issues/803
0.5
mentioned
=> Deprecations & Default RPC Provider

__tests__/account.test.ts, __tests__/cairo1.test.ts, __tests__/cairo1v2.test.ts, src/utils/transaction.ts
As no Devnet is currently supporting rpc0.5.0, I tried to use a local Pathfinder node (Testnet) with a Cairo1 account (ArgentX).
Several problems have been discovered and solved (see hereunder).
- If you try `myAccount.execute()` with a Cairo 1 account, it works fine only if you use the type `Calldata`. With `RawArgs` type, an error occurs. It's now solved. (2 people reported this problem in Discord, but I thought they have made errors in the creation of their calldata...).
- Problem of `myAccount.execute()` solved in `src/utils/transaction.ts`.
- In account.test.ts, several `declare()` have been replaced by `declareIfNot()`.
- Funding of new accounts has been reduced to minimize the gETH needs.
- Simulate or estimateFee for Declare are failing if this class is already declared (it's the …
=> fix: errors when testing in Testnet with a Cairo 1 account

src/types/api/rpcspec/nonspec.ts
Syncing was incorrectly typed it should be `false` or `SYNC_STATUS`. Ref: https://github.com/starkware-libs/starknet-specs/blob/aae966a5067e139d2b1050c2d11d47a6b41d47c9/api/starknet_api_openrpc.json#L745
- Should remove unnecessary checks
=> fix: correct syncing type

www/docs/guides/compiled_contracts/deployBraavos.ts, www/docs/guides/connect_account.md, www/docs/guides/connect_contract.md, www/docs/guides/connect_network.md, www/docs/guides/create_account.md, www/docs/guides/create_contract.md, www/docs/guides/events.md, www/docs/guides/interact.md, www/docs/guides/intro.md, www/docs/guides/migrate.md, www/docs/guides/signature.md, www/docs/guides/use_ERC20.md, www/docs/guides/what_s_starknet.js.md
Following removal of Starknet sequencers, users shall only use `RpcSequencer`.
The guides are here updated in accordance.
It's also the opportunity to migrate in the guides from Pythonic Devnet to Starknet-devnet-rs.
N/A
N/A
=> docs: use only RpcProvider

__tests__/fixtures.ts, __tests__/rpcProvider.test.ts, src/provider/rpc.ts
Should make the `waitForTransaction` configuration behave closer to user expectations.
Resolves #859
=> fix: prioritize error states in waitForTransaction evaluation

__mocks__/hellov2.ts, __tests__/cairo1_typed.test.ts, __tests__/cairo1v2_typed.test.ts, package-lock.json, package.json, src/contract/default.ts, src/contract/interface.ts, src/types/api/rpcspec/components.ts, src/types/lib/contract/abi.ts
Cairo v1 introduced many breaking changes to the ABI, this PR aims to integrate abiwan v2 which support the new cairo versions with starknet.js
Users will be able to get typed function calls on their Cairo v1 contracts, all they need to do is call the `typedv2` function and pass the ABI object
=> [Feat]: Abiwan V2 Integration

www/docs/guides/automatic_cairo_ABI_parsing.md, www/docs/guides/connect_contract.md
This PR is about documenting what has been done  in https://github.com/starknet-io/starknet.js/pull/921
...
- Change 1.
- ...
- Change 1.
- ...
=> Docs: update abiwan guides

__tests__/utils/ethSigner.test.ts, src/index.ts, src/signer/ethSigner.ts, src/signer/index.ts, src/utils/eth.ts, www/docs/guides/connect_account.md
Solve issue #888 .
```typescript
const myEthPrivateKey = "0x525bc68475c0955fae83869beec0996114d4bb27b28b781ed2a20ef23121b8de";
const myEthAccountAddress = "0x65a822fbee1ae79e898688b5a4282dc79e0042cbed12f6169937fddb4c26641";
const myEthSigner = new EthSigner(myEthPrivateKey);
const myEthAccount = new Account(provider, myEthAccountAddress, myEthSigner)
```
To obtain a randon Ethereum private key:
```typescript
const myPrivateKey = eth.ethRandomPrivateKey();
```
new EthSigner.ts file, nearly a copy/paste of Signer.ts
Tests will have to be updated once an account contract using ETH signature will be available.
=> new feature: Ethereum signer

__tests__/cairo1_typed.test.ts, package-lock.json, package.json, src/contract/default.ts, src/contract/interface.ts, www/versioned_docs/version-5.19.5/guides/automatic_cairo_ABI_parsing.md, www/versioned_docs/version-5.24.3/guides/automatic_cairo_ABI_parsing.md
This avoid `npx abi-wan-kanabi` to use the installed version and forces it to get the latest version from npm
...
- `typed` is now renamed to `typedv1`
- Change 1.
- ...
=> Chore: Rename abi-wan-kanabi to abi-wan-kanabi-v1

src/utils/calldata/enum/CairoCustomEnum.ts, src/utils/calldata/enum/CairoOption.ts, src/utils/calldata/enum/CairoResult.ts, www/docusaurus.config.js, www/package-lock.json, www/package.json
=> Add search functionnality to the official website.

package-lock.json, package.json
- This is the code for this issue: https://github.com/starknet-io/starknet.js/issues/924
- Update TS version `"typescript": "^5.3.0"` and the dependency: `"typedoc": "^0.25.7"`
I used the testing RPC from this tutorial: export TEST_RPC_URL=https://starknet-testnet.public.blastapi.io/rpc/v0.5 https://github.com/starknet-io/starknet.js/blob/main/CONTRIBUTING.md, and from infura 
- Now we can use TS 5.3 and It's features: https://devblogs.microsoft.com/typescript/announcing-typescript-5-3/
- The build still works normally
=> feat: bump TypeScript to 5.3

www/docs/guides/migrate.md, www/docusaurus.config.js
In the frame of Starknet.js v6 pre-release, added in the migration guide the recommendations to migrate from v5 to v6.
Changed the start page : migration guide from v5
Do not forget to create a last V5 documentation variant, before the pre-release.
=> docs: add migration to V6

www/docs/guides/connect_network.md
In the guides, the table of Starknet.js versions is not properly displayed.
Solved by this small PR
=> docs: solve visual display of the table for snjs versions

src/channel/rpc_0_6.ts, src/types/provider/configuration.ts
This saves an extra call on RPC for optionally-known information (like the `chainId` case).
also fixed speck -> spec typo
- [v ] Performed a self-review of the code
- [v ] Rebased to the last commit of the target branch (or merged it into my branch)
=> fix(RpcChannel): allow client to provide `specVersion`

__tests__/utils/typedData.test.ts, src/utils/typedData.ts
=> fix: expand encoding type for preset types

__tests__/account.test.ts, src/account/default.ts, src/types/account.ts, src/types/signer.ts
Signing should be skipped if skipValidate is true. There is no need for signing in this case, because we send empty signature anyways.
For example, on ledger you would need to sign a transaction even if skipValidate is true for feeEstimation which shouldn’t be the case
...
- Change 1.
- ...
- Change 1.
- ...
=> feat: don't sign when skipValidate is true

__tests__/cairo1v2.test.ts, __tests__/cairo1v2_typed.test.ts, __tests__/utils/shortString.test.ts, src/utils/calldata/byteArray.ts, src/utils/typedData.ts
Solve #1003 
If a ByteArray has less than 31 characters, the data array has to be empty (was containing one "0x00" item)
N/A
N/A
=> fix: byteArray encoding for less than 31 chars

__tests__/rpcProvider.test.ts, __tests__/utils/stark.test.ts, __tests__/utils/utils.test.ts, src/constants.ts, src/provider/rpc.ts, src/types/provider/configuration.ts, src/utils/responseParser/rpc.ts, src/utils/stark.ts
The PR alters the resource bound max amount calculation in line with the recommendation from the Starknet v0.13.1 pre-release notes. It also makes the fee margins configurable at Provider/Account class initialization.
- The max amount bound calculation is modified
- Users can fine-tune fee margins through the `ProviderOptions` constructor parameter
- The `overhead` parameter of the `estimatedFeeToMaxFee` utility function is changed from using a decimal notation to using a percentage notation (e.g. 0.2 to 20) to be in line with the `estimateFeeToBounds` function
=> Adjust max amount and make fee margins configurable

src/constants.ts, www/docs/guides/connect_network.md
In Mainnet, Goerli testnet, Sepolia Testnet, 
Blast & Nethermind public nodes are now both compatible with rpc spec v0.7.0.
Rpc spec v0.7.0 can now become the default rpc version.
Default rpc spec version was 0.6.0 ; become v0.7.0.
Documentation updated with latest status.
N/A
=> RPC_DEFAULT_VERSION bumped to v0_7

CHANGELOG.md, CONTRIBUTING.md, __tests__/config/constants.ts, __tests__/config/helpers/env.ts, __tests__/config/helpers/localDevnetDetector.ts, __tests__/config/jestGlobalSetup.ts, __tests__/rpcProvider.test.ts, __tests__/utils/stark.test.ts, __tests__/utils/utils.test.ts, package-lock.json, package.json, src/account/default.ts, src/constants.ts, src/provider/rpc.ts, src/types/provider/configuration.ts, src/utils/responseParser/rpc.ts, src/utils/stark.ts, www/docs/guides/connect_network.md
I am working with Starknet abstract account. To support our work, I am extending the starknet.js `Account` class to add some additional behaviours on the application side. I am **not** changing the way the transaction version is used internally and would still need to implement the account deployment.
You have defined 3 `private` methods in the class which makes sense to not expose to the outside. However in the context of extending that class we would prefer to access those 3 methods instead of rewriting them. Obviously, this is your decision to make. For that particular scenario, I think having those 3 `private` methods turned into `protected` makes more sense.
- not applicable
- It will not affect any user that is not extending the account class (i.e. most developers)
- It will …
=> simplify extends for the account class

src/utils/address.ts
Closes #1031 
...
- Change 1.
- ...
- Change 1.
- ...
=> docs: validateChecksumAddress

src/account/default.ts
Fix: https://github.com/starknet-io/starknet.js/issues/1029
=> fix: estimateFeeBulk include skipValidate in accountInvocationsFactory

__mocks__/typedData/example_baseTypes.json, __tests__/utils/typedData.test.ts, src/constants.ts, src/types/api/rpcspec_0_6/methods.ts, src/types/api/rpcspec_0_7/methods.ts, src/types/typedData.ts, src/utils/typedData.ts
Resolves #1002 (i128 typed data encoding). Also adds typed data range checks for primitive types and a "StarkNet" casing update for typed data types.
The encoding changes should not affect users that use valid data, if the data is outside the permitted range it will generate errors with the code from this PR. If users are using some of the updated types they will need to update them to their new name.
=> fix: repair i128 typed data encoding and add typed data range checks

www/versioned_docs/version-5.24.3/guides/events.md
Previously, at https://www.starknetjs.com/docs/guides/events#without-transaction-hash, the code contains a typo which won't run:
The users will see the correct code.
=> docs: fix nodeUrl code typo

src/channel/rpc_0_7.ts
this saves an extra call on RPC for optionally-known information (like the `chainId` case). also fixed speck -> spec typo
Fixes a rpc 0.7 degradation
0.7
- Change 1.
- ...
- Change 1.
- ...
- [ v] Performed a self-review of the code
- [ v] Rebased to the last commit of the target branch (or merged it into my branch)
- [ -] Linked the issues which this PR resolves
- [ -] Documented the changes in code (API docs will be generated automatically)
- [ -] Updated the tests
- [ v] All tests are passing
=> fix(RpcProvider): allow client to provide `specVersion` in 0.7 provider

__tests__/account.test.ts, package-lock.json, src/account/default.ts, src/account/interface.ts, src/signer/interface.ts, www/docs/guides/connect_account.md, www/docs/guides/define_call_message.md, www/docs/guides/interact.md, www/docs/guides/signature.md
Solve issue #1030 .
`Account.execute()` uses an optional `abis` parameter that is useless. Same for `Signer` interface.
- Signer optional `abis` parameter is deleted.
- `Account.execute()` accepts both signatures with and without `abis` parameter (to not break the current syntax).
All these syntaxes are valid :
```typescript
const res1 = await account0.execute(myCall,undefined,{maxFee:10n**17n});
const res2 = await account0.execute(myCall);
const res3 = await account0.execute(myCall,{maxFee:10n**17n});
```
- Abis removed of Signer interface
- Account interface with execute method overloaded.
- Added a test of the new syntax.
**Nota** : Guides are automatically modified by CI during commit. I think that this has to be deactivated. Documentation content has to be handled only by the author.
=> fix: remove unnecessary abis parameter from signer and .execute

src/account/default.ts, src/types/provider/response.ts, src/utils/responseParser/rpc.ts, www/versioned_docs/version-5.24.3/guides/events.md
With starknet 0.13.1, overall_fee is calculated with data_gas_consumed and data_gas_price. Let's expose this if wallets or dapps wants to use it
0.7
- Change 1.
- ...
- Change 1.
- ...
=> chore: expose data gas consumed and data gas price for 0.7 rpc

src/utils/provider.ts, www/docs/guides/L1message.md, www/docs/guides/connect_network.md, www/docs/guides/create_account.md, www/docs/guides/interact.md, www/docs/guides/migrate.md, www/docs/guides/signature.md, www/docs/guides/what_s_starknet.js.md
Starknet Goerli testnet has been shut down yesterday.
Documentation has been updated accordingly.
> At the same time, a small update in migrate.md has been made.
default network has been changed to SEPOLIA.
> data in constants.ts have not been modified, because it has to be modified also for get-starknet and compatibility with L3 (enum -> string).
=> Doc : Goerli deprecated

src/utils/calldata/requestParser.ts
Documentation site build is generating an error : 
```
SyntaxError: /D/starknetFork/starknet.js/www/docs/API/modules.md: Expected corresponding JSX closing tag for <any>. (976:86)
```
The problem is in the JSDoc of `export function parseCalldataField()`, where the word `<any>` is not authorized.
N/A
N/A
=> fix in doc: word <any> not authorized in jsdoc

CONTRIBUTING.md, README.md, www/docusaurus.config.js
=> chore: added discord link to all relavant places

src/provider/extensions/starknetId.ts
We will soon update the starknet ID `naming` contract function `address_to_domain`, adding an additional `hint` parameter that will allow us to support CCIP reverse resolving of domains. This change will break `getStarkName` & `getStarkProfile`. In prevision of this, to avoid any errors for people using these functions, I updated them so that they will first try to make the query with the new `hint` parameter, and if it fails try without.
=> refactor: getStarkName & getStarkProfile to work with latest version of contract

src/utils/transaction.ts
To provide developers with typescript examples in JsDoc
Run examples as seen in the document
provide examples for developers
- [x ] Performed a self-review of the code
- [x ] Rebased to the last commit of the target branch (or merged it into my branch)
- [x ] Linked the issues which this PR resolves
- [x ] Documented the changes in code (API docs will be generated automatically)
- [x ] All tests are passing
=> chore: add examples to JsDoc for transaction.ts file

__tests__/account.test.ts, __tests__/config/fixtures.ts, src/channel/rpc_0_7.ts, src/provider/rpc.ts, src/types/provider/configuration.ts, src/utils/url.ts
Resolves #937
As mentioned in the issue above, there's a colossal test slowdown between v5 and v6. The problem was with the `retryInterval` for `waitForTransaction` for the `devnet` test env, which was overridden in the `fixtures`. This one now does not work because of the `ts-mixer` used to merge the base provider and `starknet classes. The ts-mixer library doesn't directly support overriding methods on instances after mixing. Mixins in ts-mixer are classes with properties and methods that get merged into the target class during compilation. This creates a new class with the combined functionality but doesn't allow runtime modification of existing instances.
The issue mentions only `account.test`, affecting all tests. That being said, this should improve all test performance.
**Account …
=> test: Improve tests performance

.gitignore, CONTRIBUTING.md, package-lock.json, package.json, src/types/lib/contract/abi.ts, src/utils/assert.ts, src/utils/calldata/formatter.ts, src/utils/calldata/index.ts, src/utils/calldata/parser/parser-2.0.0.ts, src/utils/eth.ts, src/utils/responseParser/index.ts
This PR adds new `ts:coverage`and `ts:coverage:report` npm scripts that use [type-coverage](https://www.npmjs.com/package/type-coverage) and [typescript-coverage-report](https://www.npmjs.com/package/typescript-coverage-report) to display the global type coverage and to generate a TypeScript coverage summary in the console and a full report in HTML.
Resolves: https://github.com/starknet-io/starknet.js/issues/1088
0.7.1
None
New npm scripts added: `ts:coverage` and `ts:coverage:report`
=> feat: add type coverage

src/account/default.ts, src/utils/stark.ts, src/wallet/account.ts, src/wallet/connect.ts
the externalization of types in starknet-types that come with starknet.js 6.8 prevents typescript from inferring types that are not available in the project. To workaround this issue, this commit declares the SPEC type, helping the typescript inference.
The typescript language server reports 4 errors like the one below in the project :
```
The inferred type of 'signMessage' cannot be named without a reference to
'../../node_modules/starknet-types-07/dist/types/api/components'. This is likely
not portable. A type annotation is necessary.ts(2742)
function signMessage(swo: StarknetWindowObject, typedData: TypedData): Promise<SIGNATURE>
```
> Note: this error does not prevent the build
0.7
None
None
=> fix: cannot infer (TS2742) types from starknet-types@0.7

.github/workflows/_test.yml, __tests__/config/fixtures.ts, src/account/interface.ts, src/channel/rpc_0_6.ts, src/channel/rpc_0_7.ts, src/provider/interface.ts, src/provider/rpc.ts, src/signer/interface.ts, src/types/account.ts, src/types/provider/configuration.ts, src/types/provider/response.ts, src/utils/calldata/byteArray.ts, src/utils/calldata/index.ts, src/wallet/connect.ts
running `npx typedoc --entryPoints src --out build` generates a number of warnings that are addressed here.  This PR replaces #1092. It is based on `next-version` and the changes are now split by commits so that they are easy to understand and if needed can be cherry-picked
Some of the issues addressed that are small enhancements to use the starknet.js library. Others are more opinionated or improvements. For a better understanding, changes have been grouped per commits. This is the list of commits and fixes:
- fix: rename the @param to match the definitions
- fix: add a space before typedoc \<br/\> so that it catches the name
- fix: improve function declaration so that typedoc matches it
- fix: reintroduce the parameter name
- fix: remove unused type declaration and export
- ~~fix: …
=> fix: remove [warning] from typedoc for external usage

www/docs/guides/connect_account.md, www/docs/guides/create_account.md
Documentation of Eth Randomness of private key  is located today in the `connect to an existing account`.
It's better to locate this subject in `Create an account` guide.
See above.
N/A
=> Relocate documentation of Eth priv key randomness

src/utils/provider.ts
Solves issue #1136
N/A
As proposed by @tabaktoni  in issue #1136, 2 functions that are useful only for the deprecated sequencer are removed :
- ` utils/provider.ts/formatHash`
- `utils/provider.ts/txidentifier`
=> refactor: remove functions useful only for deprecated sequencer

LICENSE, README.md, package.json
- remove author
- licence to Starkware
- readme cleanup
=> docs: update licence, package, readme

.eslintrc, build.config.ts, package-lock.json, package.json, tsup.config.ts
It fixes #1137
Currently, the `tsup` build tool produces issues in build time when using re-exported same-named values and constants (companion pattern). TLDR: The build output is not correct, which results in correct types, but the constant cannot be recognized by a TS when using the `starknet` package. So, I introduced [unjs/unbuild](https://github.com/unjs/unbuild) for `cjs` and `ejs` output format.
7
_n.a_
- Add `unjs/unbuild` additional build tool
=> chore: Introduce unjs/unbuild

__tests__/utils/typedData.test.ts, src/utils/typedData.ts
related to #1090 
...
- Change 1.
- ...
- Change 1.
- ...
=> docs: added examples and tests for typedData

__tests__/utils/batch.test.ts, package-lock.json, package.json, src/signer/ledgerSigner.ts, src/utils/url.ts
Resolves #1189. Also marks the url utility methods as deprecated.
None.
The ledger `Transport` typing will not be available out of the box. A workaround is listed in the corresponding code comments.
=> fix: remove ledger transport dependency

__tests__/account.test.ts, src/account/default.ts, src/provider/rpc.ts, src/types/account.ts, src/types/lib/index.ts
Fix #1209
- Implement TransactionType Fix from #1193 to be able to use TS Invocations properly
New
Test if class is already declared from `ContractClassIdentifier`
```ts
provider.isClassDeclared(contractClassIdentifier: ContractClassIdentifier, blockIdentifier?: BlockIdentifier)
```
Build _bulk_ invocations with auto-detect declared class and declare order sort
~~provider.createBulkInvocations(invocations: Invocations)~~
```ts
provider.prepareInvocations(invocations: Invocations)
```
=> feat: isClassDeclared  createBulkInvocations, fix cairo0 test

src/types/lib/index.ts
It resolves: #1216
...
- Change 1.
- ...
- Change 1.
- ...
=> fix: remove dupe values type import

.github/workflows/_test.yml, __tests__/config/fixtures.ts
- shardlabs/starknet-devnet-rs:0.2.0-rc.2
=> fix: bump devnet, hotfix devnet create block

__tests__/utils/calldata/requestParser.test.ts, src/utils/calldata/requestParser.ts, src/utils/calldata/responseParser.ts, src/utils/calldata/validate.ts
Cover calldata `requestParser` with tests
...
- Change 1.
- ...
- Change 1.
- ...
=> chore: introduce calldata `requestParser.test.ts`

www/docs/guides/outsideExecution.md
OpenZeppelin account 0.17.0 is now compatible with SNIP-9.
Documentation has been modified to integrate OpenZeppelin in the list of compatible accounts
Tests have been done with both Starknet & Ethereum signatures versions :
https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/main/src/scripts/Starknet132/Starknet132-devnet/2.accountOZ17snip-9.ts
https://github.com/PhilippeR26/starknet.js-workshop-typescript/blob/main/src/scripts/Starknet132/Starknet132-devnet/3.accountOZ17EthSnip-9.ts
=> docs: add Openzeppelin as SNIP-9 compatible

www/docs/guides/walletAccount.md
Just 2 little corrections in the WalletAccount guide
- missing `@starknet-io/` in lib name
- use at least v4.0.3 to be able to handle Metamask Snap.
=> WalletAccount guide: correction of lib name

www/docs/guides/automatic_cairo_ABI_parsing.md, www/docs/guides/cairo_enum.md, www/docs/guides/estimate_fees.md
This PR corrects minor typographical errors in the documentation files, enhancing readability and accuracy. 
1. **automatic_cairo_ABI_parsing.md**
- Changed "wrap your ABI in a array" to "wrap your ABI in an array".
2. **cairo_enum.md**
- Corrected "an other core Enum" to "another core Enum".
3. **estimate_fees.md**
- Changed "nonfree Starknet commands" to "non-free Starknet commands".
These changes improve the documentation by fixing minor errors, making the documentation clearer for users without altering any functional content.
There are no code changes; this PR only updates the documentation.
=> Fix: correct typos in documentation

__tests__/WebSocketChannel.test.ts, __tests__/utils/stark.browser.test.ts
This PR contains small tweaks to stabilize the tests:
- moving the `WebSocketChannel` initializations into setup hooks ensures they are bound to their respective `describe` scopes and properly followed by the teardown hooks, without the change they are treated as if they were in the same higher scope causing one of them to be orphaned in case of errors
- removing the underlying `isows` dependency with a mock allows the tests from `utils/stark.browser.test.ts` to run
=> test: stabilize websocket tests

__tests__/cairo1v2.test.ts, __tests__/cairo1v2_typed.test.ts, __tests__/config/customMatchers.ts, __tests__/config/jest.setup.ts, __tests__/contract.test.ts, __tests__/utils/events.test.ts, src/contract/default.ts, src/types/contract.ts, src/utils/events/index.ts
`provider.getEvents` method returns list of `EmittedEvents` which contains fields for block number, block hash and transaction hash. Parsing list of those events with `parseEvents` would drop those fields. This PR adds them back to the returned array if they are available.
...
Users now use additional data from parsed events structure.
N/A
=> feat: add support for parsing emitted events

__tests__/rpcChannel.test.ts, __tests__/rpcProvider.test.ts, __tests__/utils/batch.test.ts, src/channel/rpc_0_6.ts, src/channel/rpc_0_7.ts, src/types/provider/configuration.ts, src/utils/batch/index.ts
Enables a base `fetch` override for the channel classes and ensures the same `fetch` is used within the underlying `BatchClient`. This is the first step of the `isomorphic-fetch` and `fetch-cookie` dependency removal.
=> feat: enable base fetch override

__tests__/utils/typedData.test.ts, src/utils/typedData.ts
=> fix: correct enum typed data hashing

__tests__/utils/typedData.test.ts, src/utils/typedData.ts
=> fix: snip-12 violation with extra `:` in enum encoding

src/account/default.ts
There is a bug in current bulk fee estimation or simulation because of accountInvocationsFactory not passing signerDetails.
It throws error when buildTransaction is called here
https://github.com/starknet-io/starknet.js/blob/698461950333c1df6cef302e1947e1012c3097f4/src/channel/rpc_0_7.ts#L435
Because `tip` was `undefined`
https://github.com/starknet-io/starknet.js/blob/698461950333c1df6cef302e1947e1012c3097f4/src/channel/rpc_0_7.ts#L664
...
- Change 1.
- ...
- Change 1.
- ...
=> fix: pass signerDetails to fix estimateFeeBulk

__tests__/account.starknetId.test.ts, src/provider/extensions/starknetId.ts, src/utils/starknetId.ts
Argent ran into a problem using `useDecoded` when decoding the domain `Grug.stark`, this should have been passed as `grug.stark` but they didn't have the `isStarkDomain` to do so easily. 
I'm addding two things to help wallet and devs in general:
1. Adding `isStarkDomain` to permit manual verification
2. Refactoring `getAddressFromStarkName` to make the function detect this kind of name errors in the future
=> fix: add starkid improvements

__tests__/utils/utils.test.ts, src/index.ts, src/utils/units.ts
Requested by dev from HH Bangkok similar to https://viem.sh/docs/utilities/formatUnits
Convert fri to strk
```ts
units(1n, 'fri')
```
convert strk to fri
```ts
units('0.3', 'strk')
```
=> feat: units utils

__tests__/account.outsideExecution.test.ts, src/account/default.ts, src/utils/outsideExecution.ts, www/docs/guides/outsideExecution.md
Solves issue #1263 .
User are requesting to add functions for executors of SNIP-9 outside executions, allowing them to estimate the fees they will have to pay and to simulate a SNIP-9 transaction.
On executor side, if you want to estimate how many fees you will pay:
```typescript
const outsideExecutionCall: Call[] =
outsideExecution.buildExecuteFromOutsideCall(outsideTransaction1);
const estimateFee = await executorAccount.estimateFee(outsideExecutionCall);
```
On executor side, if you want to simulate the transaction:
```typescript
const outsideExecutionCall: Call[] =
outsideExecution.buildExecuteFromOutsideCall(outsideTransaction1);
const invocations: Invocations = [
{
type: TransactionType.INVOKE,
payload: outsideExecutionCall,
},
];
const responseSimulate = await …
```
=> feat: outside execution: add estimate fees and simulate

src/utils/cairoDataTypes/uint256.ts
Fixed typo in the documentation comments of the CairoUint256 class where "uin256" was incorrectly used instead of "uint256" in the constructor documentation.
=> Fix typo in CairoUint256 class documentation

__tests__/account.starknetId.test.ts, __tests__/account.test.ts, __tests__/cairov24onward.test.ts, __tests__/rpcProvider.test.ts, __tests__/transactionReceipt.test.ts, __tests__/utils/ellipticalCurve.test.ts, __tests__/utils/ethSigner.test.ts, __tests__/utils/merkle.test.ts, __tests__/utils/transaction.test.ts, __tests__/utils/typedData.test.ts, __tests__/utils/uint256.test.ts, __tests__/utils/utils.test.ts, src/account/default.ts, src/account/interface.ts, src/contract/default.ts, src/index.ts, src/provider/interface.ts, src/provider/rpc.ts, src/types/lib/index.ts, src/utils/cairoDataTypes/felt.ts, src/utils/encode.ts, src/utils/json.ts, src/utils/num.ts, src/utils/stark/index.ts, src/utils/transaction.ts, src/utils/typedData.ts, src/utils/uint256.ts, src/wallet/account.ts
Removes long-standing deprecated functionalities and aliases.
Notes:
- the `ProviderInterface. invokeFunction()` deprecation seems to have been based on traits stemming from before the RPC support was introduced, it seems to have been made obsolete by the introduction of the `details` parameter - it is internally used so just the deprecation mark is removed
- the `WalletAccount` change could be made stricter by making the constructor private and introducing an optional `address` parameter to the `connect` methods to potentially skip the address retrieval
=> feat: prune deprecated functionalities

__tests__/utils/address.test.ts, src/utils/address.ts
Resolves #1258 
The `addAddressPadding` utility is adjusted to use numeric inputs as values rather than their string equivalents.
=> fix: preserve value for numeric arguments within address padding utility

www/docs/guides/migrate.md
Update of the migration to V7 documentation.
modified migration guide
N/A
=> docs: update migration to v7

__tests__/rpcProvider.test.ts, src/account/default.ts, src/provider/rpc.ts
Ensures that `RpcProvider.create(...)` generates the chosen class with the appropriate TypeScript type for both the base class and extended classes after mixins are added. Also disables it for the `Account` class inheritance chain.
=> fix: make the provider create method generic to enable it when mixins are applied

src/global/constants.ts, src/types/outsideExecution.ts
Completes the transition from TS enums into their companion pattern replacements. Also repairs the reachability of the `SupportedRpcVersion` object that was being hidden by the type in the distribution build.
=> fix: ensure enum replacement objects are reachable for type resolution

src/provider/rpc.ts
We have 3 new methods in Rpc 0.8:
- `getL1MessagesStatus()`
- `getStorageProof()`
- `getCompiledCasm()`
Methods have been created, but are not accessible in `RpcProvider` instance.
This is not working:
```typescript
myProvider.getStorageProof();
```
A workaround is:
```typescript
(myProvider.channel as RPC08.RpcChannel).getStorageProof();
```
Now these methods are working:
- `myProvider.getL1MessagesStatus()`
- `myProvider.getStorageProof()`
- `myProvider.getCompiledCasm()`
Several problems solved in `src/provider/rpc.ts`.
=> fix: new rpc08 methods are not accessible in RpcProvider

src/signer/index.ts, src/signer/ledgerSigner221.ts, src/signer/ledgerSigner231.ts, www/docs/guides/signature.md
Handling of Rpc 0.8 v3 transaction by Ledger Nano hardware wallet v2.3.1:
APP is not yet public (should be released this week).
`LedgerSigner221` class has to be replaced by `LedgerSigner231`.
This new class is compatible:
- Rpc 0.7
- tx V1
- tx V3
- Rpc 0.8
- tx V3
`getLedgerPathBuffer221` is valid for LedgerSigner231.
- Encoding of Ledger messages has been deeply modified by Ledger.
- All functionalities have been tested in Rpc 0.7 & 0.8, V1 & V3, Ledger Nano S+ & X.
- Tested in Node.js and in a Next.js DAPP.
=> feat: handling of Ledger Starknet APP v2.3.1

__tests__/utils/ethSigner.test.ts
This pull request removes a duplicate `describe('Ethereum address')` block in the test suite. Having two identical test blocks is redundant.
N/A
No changes to the public API or user interface. This change only has internal testing implications.
- Removed a test copy block, less redundant and clearer in the test suite.
=> test: remove duplicated Ethereum address test block

src/utils/transactionReceipt/transactionReceipt.ts, src/utils/transactionReceipt/transactionReceipt.type.ts, www/docs/guides/events.md
- `GetTransactionReceiptResponse`'s methods `isSuccess()`, `isError()`, `isReverted()` is no longer narrow the right type.
- Documentation wrongly quotes usage of `txReceipt`
=> update proper type predicates for `GetTransactionReceiptResponse` and `ReceiptTx`
No changes
No changes
=> fix: isSuccess, isError, isReverted type predicate of ReceiptTx, GetTransactionReceiptResponse

__tests__/accountPaymaster.test.ts, __tests__/defaultPaymaster.test.ts, package-lock.json, package.json, src/channel/ws_0_8.ts, src/provider/types/response.type.ts, src/provider/types/spec.type.ts, src/types/api/index.ts, src/types/contract.ts, src/types/errors.ts, src/types/lib/contract/abi.ts, src/types/lib/contract/legacy.ts, src/types/lib/index.ts, src/types/typedData.ts, src/utils/outsideExecution.ts, src/utils/paymaster.ts, src/utils/stark/index.ts, src/wallet/account.ts, src/wallet/connect.ts, src/wallet/types.ts
Prevent future attempts to create false packages by using organization-named aliases.
=> feat: rename internal type-js alias to organization

www/docs/guides/connect_network.md, www/docs/guides/create_account.md, www/docs/guides/doc_scripts/deployBraavos.ts, www/docs/guides/interact.md, www/docs/guides/migrate.md, www/docs/guides/walletAccount.md
These 2 modifications have not been reported in the guides:
- Nethermind public node removed.
- Rpc version is now on 3 digits
N/A
N/A
=> docs: nethermind removed. rpc version 3 digits

__tests__/utils/typedData.test.ts, src/utils/typedData.ts
Allows a numeric revision value for typed data.
=> fix: allow numeric revision value for typed data

__tests__/WebSocketChannel.test.ts, __tests__/account.outsideExecution.test.ts, __tests__/account.starknetId.test.ts, __tests__/account.test.ts, __tests__/cairo1v2.test.ts, __tests__/cairo1v2_typed.test.ts, __tests__/cairov24onward.test.ts, __tests__/config/fixtures.ts, __tests__/config/fixturesInit.ts, __tests__/config/helpers/initDevnetHistory.ts, __tests__/config/helpers/strategyResolver.ts, __tests__/config/jestGlobalSetup.ts, __tests__/contract.test.ts, __tests__/defaultProvider.test.ts, __tests__/rpcChannel081.test.ts, __tests__/rpcChannel09.test.ts, __tests__/rpcProvider.test.ts, __tests__/transactionReceipt.test.ts, __tests__/utils/batch.test.ts, __tests__/utils/ethSigner.test.ts, __tests__/utils/tip.test.ts, __tests__/utils/utils.test.ts, www/docs/guides/what_s_starknet.js.md, www/versioned_docs/version-6.11.0/guides/what_s_starknet.js.md, www/versioned_docs/version-6.23.1/guides/what_s_starknet.js.md, www/versioned_docs/version-6.24.1/guides/what_s_starknet.js.md, www/versioned_docs/version-7.6.4/guides/what_s_starknet.js.md
When executing the test suite in Devnet, we have a flood of tip error messages.
Devnet is starting from block 0 (no history of transactions) and creates a new block at each transaction. So, the default `maxBlocks` and `minTxsNecessary` are not adapted for Devnet.
This PR create a small initiial history of Devnet transactions, and is changing the default values (only for Devnet)
N/A
- if Devnet is just launched (zero blocks), 3 random transactions are created, with random tips, to create an initial tip history.
- account.getEstimateTip() is overwritten when using Devnet, to use new default values:
```ts
minTxsNecessary: options.minTxsNecessary ?? 3,
maxBlocks: options.maxBlocks ?? 10,
```
- To create these 3 new transactions before launching the test suite, some parts of …
=> test: modify estimation of tip for Devnet

src/types/index.ts
Ensures a Buffer type is available for development environments without Node.js types.
=> fix: ensure a Buffer type is available for all environments

__tests__/utils/cairoDataTypes/CairoByteArray.test.ts, __tests__/utils/cairoDataTypes/CairoBytes31.test.ts, src/utils/cairoDataTypes/byteArray.ts, src/utils/cairoDataTypes/bytes31.ts, src/utils/cairoDataTypes/felt.ts
Resolves the latest issue described in #1477.
Modifies the initialization of `CairoBytes31`, `CairoFelt252`, and consequently `CairoByteArray` to be more uniform, and adjusts their output methods to be better aligned with how RPC nodes communicate.
The main change is that for the `CairoBytes31` class the `data` `Uint8Array` will always be initialized to the exact size of 31 regardless of input size. As an example, `new CairoBytes31('0x1')` and `new CairoBytes31('0x0001')` will both have the value of `data` set to `[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]`.
A similar change is made to `CairoFelt252`, the underlying `data` isn't prepended with zeros to match a fixed size like with `CairoBytes31`, and is instead truncated to exclude …
=> fix: enforce fixed size for cairo bytes
