__tests__/ellipticalCurve.test.ts
src/ellipticalCurve.ts

fix: msgHash length check fix in signature verify function

---

src/provider/default.ts
src/provider/interface.ts
src/signer/default.ts
src/signer/interface.ts
src/types.ts

Trying to match Starkware's code quality before mainnet launch

Rename some to 'tx' to 'transaction'

---

CHANGELOG.md
__tests__/utils/shortString.test.ts
__tests__/utils/uint256.test.ts
package-lock.json
package.json
src/constants.ts
src/contract.ts
src/index.ts
src/provider/default.ts
src/provider/interface.ts
src/signer/default.ts
src/signer/interface.ts
src/types.ts
src/utils/shortString.ts
src/utils/stark.ts
src/utils/uint256.ts

This release adds shortString and uint256 capabilities
please merge if you approve :-)

Release 2.3.1

---

__tests__/signer.test.ts
src/signer/default.ts
src/types.ts

feat: allow custom nonce

---

__tests__/provider.test.ts
src/provider/default.ts
src/provider/interface.ts
src/types.ts

feat: introduce blockNumber

---

src/provider/default.ts

Add response to the waitForTx error

---

__tests__/provider.test.ts
src/provider/default.ts
src/provider/interface.ts
src/provider/utils.ts

- Add block hash to API
- Update GitHub reference to 0.6.2
- Fixes test cases to use new transactions and contracts (old ones tend to error out)

feat(blockHash): add blockHash and fix test cases

---

CONTRIBUTING.md

Reverts seanjameshan/starknet.js#107

Revert "fix: wrong link"

---

README.md

There were a couple of errors and omissions that prevent the code sample in the README from running. They should be obvious from the diff of the file.

Minor fix to code section in README.md

---

__tests__/utils/address.test.ts
src/constants.ts
src/index.ts
src/utils/address.ts

feat(utils): add validateAndParseAddress function

---

__tests__/provider.test.ts
package-lock.json
src/provider/default.ts
src/provider/interface.ts
src/provider/utils.ts

Usage like `getBlock(undefined, 3003)` is very uncommon is JS.
Therefore I introduced an easy pattern to allow blockhash and blockid

fix: introduce block identifier type

---

__tests__/provider.test.ts
src/provider/default.ts
src/provider/interface.ts
src/provider/utils.ts
src/types.ts

feat(provider): add getTransactionReceipt()

---

src/contract/default.ts
src/contract/interface.ts

needed to accept other account than the default account with the contract class
needed ie for argent x, as we implement our own account using the interface and dont use the default one.

fix: contract interface

---

package-lock.json
package.json
src/signer/index.ts
src/signer/ledger.ts

Add a Ledger signer + blind signing support only

feat: add LedgerSigner class + blind signing

---

__tests__/account.test.ts
__tests__/accountContract.test.ts
__tests__/constancts.ts
__tests__/contract.test.ts
__tests__/provider.test.ts
src/account/default.ts
src/account/interface.ts
src/contract/default.ts
src/provider/default.ts
src/provider/interface.ts
src/types/api.ts

- Contract expanded with estimate fee
- Provider expanded with transaction trace

Support 0.8.0

---

__tests__/utils/uint256.test.ts
src/utils/number.ts

Reverts 0xs34n/starknet.js#147

Revert "feat: add BigInt support within BigNumberish"

---

__tests__/utils/utils.test.ts
package-lock.json
src/account/default.ts
src/contract/default.ts
src/signer/default.ts
src/types/api.ts
src/types/lib.ts
src/utils/hash.ts
src/utils/stark.ts

- Adding options extraction in build invoke function

Fix invoke override

---

src/utils/encode.ts
www/docusaurus.config.js

closes #175 
as that PR was pointing to main
and
closes #176 
because that PR had no conventional commit messages

fix community issues

---

package-lock.json
package.json
src/utils/typedData/types.ts
src/utils/typedData/utils.ts

fix: remove superstruct

---

src/provider/default.ts
src/provider/interface.ts
www/docs/API/provider.md

docs: documentation for provider getTransactionStatus

Fix documentation and comments for provider getTransactionStatus 

---

__tests__/provider.test.ts
src/types/api.ts

fix: update api typings

---

.npmignore

Add `.npmignore` file to prevent from publishing `.github` `node_modules` `tsconfig.json`

feat(npm): add npmignore file

---

__tests__/fixtures.ts

fix(test): for new devnet version

---

src/provider/default.ts
www/docs/API/account.md
www/docs/API/contract.md
www/docs/API/contractFactory.md
www/docs/API/provider.md
www/guides/account.md
www/guides/erc20.md

Updated documentation with changes in v4

Documentation v4

---

src/types/api.ts
www/docs/API/provider.md

fix https://github.com/0xs34n/starknet.js/issues/255

feat(cairo-0.9.1): starknet_version in block response

---

__tests__/utils/address.test.ts
src/utils/address.ts
src/utils/hash.ts

changes the hashing algo for checksum addresses from pedersen to keccak
this enables more efficient address checksum computation on x86

feat: change checksum address hashing algorithm

---

www/docs/API/contract.md

Change 'small amount of EVM code' to 'small amount of cairo code' in contract.md

fix typo in contract.md

---

www/docs/API/account.md
www/docs/API/contract.md
www/docs/API/contractFactory.md
www/docs/API/provider.md
www/docs/API/signer.md
www/docs/API/utils.md

...
...
- Change 1.
- ...
- Change 1.
- ...

Ivpavici docs refactor [skip ci]

---

.gitignore
__tests__/defaultProvider.test.ts
__tests__/rpcProvider.test.ts
__tests__/sequencerProvider.test.ts
src/provider/rpc.ts
src/provider/utils.ts
src/types/api/openrpc.ts
src/types/api/rpc.ts
src/types/provider.ts
src/utils/ellipticCurve.ts
src/utils/responseParser/rpc.ts
src/utils/responseParser/sequencer.ts

Test not passig for getBlock(blockIdentifier=latest) because RPC diverged from Sequncer result.
RPC can return now different results, in one case it returns param:
```timestamp // The time in which the block was created```
Sequencer return always the same result with param
```accepted_time // When the block was accepted on L1```
GetBlock RPC results in two cases:
1.BLOCK_WITH_TX_HASHES
- status
- BLOCK_HEADER
- block_hash
- parent_hash
- block_number
- new_root
- timestamp
- sequencer_address
- BLOCK_BODY_WITH_TX_HASHES
- transactions
2.PENDING_BLOCK_WITH_TX_HASHES
- timestamp
- sequencer_address
- parent_hash
- BLOCK_BODY_WITH_TX_HASHES
- transactions
DIFF:
accepted_time?: number; 		// SEQUENCER
timestamp?: number;			// RPC IN BOTH CASES
block_hash: string;			// RPC IN CASE 1, SEQUENCER …

Breaking test Issue Example RPC common interface

---

src/provider/rpc.ts

Resolve https://github.com/0xs34n/starknet.js/issues/323
2.0
- Users should be able to pass abi to `starknet_addDeclareTransaction` and `starknet_addDeployTransaction`
- Change 1.
- ...
- [] Updated the tests

feat: optional abi field for deploy and declare rpc transactions

---

package.json

jest uses VM for running tests. Math operations (which there are many in crypto projects) can get slow because of this. We can improve that by passing it a Math global.
In my case, running non-RPC testsuites it reduced time it takes for tests to complete from 53s to 5s.
- Add [`sandboxInjectedGlobals`](https://jestjs.io/docs/configuration#sandboxinjectedglobals-arraystring) jest setting to improve speed of tests with Math intensive operations.
Compare `yarn jest` between master and this branch.
Apply this diff to only run tests that are network independent:
```diff
diff --git a/__tests__/account.test.ts b/__tests__/account.test.ts
index 214f35b..70e3e49 100644
--- a/__tests__/account.test.ts
+++ b/__tests__/account.test.ts
@@ -5,7 +5,7 @@ import { Account, Contract, Provider, number, …
```

test: use sandboxInjectedGlobals to speedup jest tests

---

__tests__/defaultProvider.test.ts
__tests__/rpcProvider.test.ts
__tests__/utils/utils.test.ts
src/provider/rpc.ts
src/provider/sequencer.ts
src/provider/utils.ts
src/types/api/openrpc.ts
src/types/api/rpc.ts
src/utils/responseParser/rpc.ts

fix https://github.com/0xs34n/starknet.js/issues/306
fix https://github.com/0xs34n/starknet.js/issues/305
This is still work in progress branch but as it contains missing RPC endpoints it should be good to implement now and subsequential completion done later.
0.1.0
- getBlockHashAndNumber
- getClassHashAt
- getPendingTransactions
- getProtocolVersion (with throw error as pathfinder didn't implement it)
- getStateUpdate
- getClass
- traceTransaction (without throw but expect not imeplelemned method resposen)
- traceBlockTransactions (without throw but expect not imeplelemned method resposen)
- BlockIdentifierClass, getIdentifier, getBlockIdentifier and getFormattedBlockIdentifier replaced with single Block Class. It is used both for RPC body identifier params and Sequencer query …

RPC Improvements

---

__tests__/defaultProvider.test.ts
__tests__/sequencerProvider.test.ts
src/types/api/sequencer.ts
www/docs/API/provider.md

Fix #340 
...
...
- Change 1.
- ...
- Change 1.
- ...

fix: adapted transactionTrace response

---

www/guides/account.md

Update the link of Argent's account
...
...
- Change 1.
- ...
- Change 1.
- ...

📝 www: update argent account

---

src/types/api/sequencer.ts
src/types/provider.ts
src/utils/responseParser/sequencer.ts

Fix https://github.com/0xs34n/starknet.js/issues/348
Spread response object and left modified props.

fix: sequencer getBlock response

---

__tests__/defaultProvider.test.ts

fix: remove status_data as it is optional response parameter

---

src/contract/default.ts

Fix https://github.com/0xs34n/starknet.js/issues/359
Fix Optional address in contract constructor

fix issue 359

---

src/contract/default.ts
src/types/lib.ts
src/utils/hash.ts
www/docs/API/account.md
www/docs/API/provider.md

Ivpavici docs [skip ci]

---

src/provider/rpc.ts
src/types/provider.ts
src/utils/responseParser/rpc.ts
src/utils/responseParser/sequencer.ts

Fix https://github.com/0xs34n/starknet.js/issues/352
0.1.0
provide all available data from Sequencer GetTransaction
provide all available data from RPC GetTransactionReceipt

Fix issue 352

---

.github/workflows/pr.yml
.github/workflows/release.yml

Uses the newest and greatest starknet-devnet image in CI

ci: use newest devnet image

---

src/provider/rpc.ts
src/provider/sequencer.ts
www/docs/API/provider.md

Enable configuring custom fetch headers.
Example
```
const provider = new Provider({
sequencer: {
baseUrl: '',
feederGatewayUrl: '',
gatewayUrl: '',
headers: {
'Authorization': 'Basic ...=='
}
},
});
```

enable custom providers headers option

---

__tests__/fixtures.ts
src/provider/sequencer.ts

Updates for testnet2 and PR to restart worflow

feat: testnet2

---

__tests__/defaultProvider.test.ts
__tests__/udc.test.ts
src/provider/rpc.ts

- Default provider test cleanup/refactor
- RPC getClassAt default blockIdentifier

test: defaultProvider clenup

---

__tests__/defaultProvider.test.ts
__tests__/fixtures.ts
src/provider/default.ts
src/provider/interface.ts
src/provider/sequencer.ts

feat: fill in sequencer class methods

---

.github/workflows/pr.yml
.github/workflows/release.yml
__tests__/account.test.ts
src/account/default.ts
src/account/interface.ts
src/constants.ts
src/types/lib.ts
src/types/provider.ts

Adds `estimateDeployFee` for UDC Deploys

fix: add estimateDeployFee

---

__tests__/contract.test.ts
package-lock.json
package.json
src/account/default.ts
src/account/interface.ts
src/provider/default.ts
src/provider/interface.ts
src/provider/rpc.ts
src/provider/sequencer.ts
src/signer/default.ts
src/signer/interface.ts
src/types/api/index.ts
src/types/api/sequencer.ts
src/types/index.ts
src/utils/hash.ts
src/utils/responseParser/rpc.ts
src/utils/responseParser/sequencer.ts
tsup.config.ts

fix: flatten main type export and import

---

package.json

fix: package json exports

---

README.md

Fixed the URL for an guide and a site.

fixed URL links [skip ci]

---

CODE_OF_CONDUCT.md

Create CODE_OF_CONDUCT.md [skip ci]

---

__tests__/utils/starknetId.test.ts
src/utils/starknetId.ts

Hey, 
Toni asked me to add deterministic random with a seed on my tests. 
Here it is. I used ``sinus`` to make a pseudo-random function that is deterministic.
I also changed the ``useEncode`` and ``useDecoded`` for better management of non-latin characters.

fix: add deterministic tests

---

__tests__/account.test.ts

fix: lib chainid test

---

__tests__/contract.test.ts

Reformat Contract test in one desc block to try to resolve nonce issue on release

test: bump release

---

__tests__/account.test.ts

Contract multi-deploy didn't wait for transaction

test: fix contract test nonce issue

---

__tests__/defaultProvider.test.ts
__tests__/fixtures.ts
__tests__/rpcProvider.test.ts
package.json
src/provider/default.ts

Adds a type check that also affects tests to improve consistency.

test: add ts compilation check to pretest step

---

.github/workflows/manual-devnet.yml
.github/workflows/manual-release.yml
.github/workflows/manual-testnet.yml
.github/workflows/pr.yml
.github/workflows/release.yml
.gitignore
.npmignore
package.json

- limits the files included in the published module to only the necessary files
- updates the workflow tests to remove deprecation warnings and prunes unnecessary step elements

ci: prune the published module

---

CONTRIBUTING.md

docs: clarify pull request targets

---

__tests__/rpcProvider.test.ts
src/provider/default.ts
src/provider/interface.ts
src/provider/rpc.ts
src/provider/sequencer.ts

refactor: cache RPC provider chain id

---

__tests__/defaultProvider.test.ts
__tests__/fixtures.ts
package-lock.json
src/provider/errors.ts
src/provider/rpc.ts
src/provider/sequencer.ts

Addresses a bug noticed in issue #417 where unsuccessful transaction retrieval results in a parsing error. The PR ensures that the `SequencerProvider` throws a custom error to make the operation state clear for developers and align the behaviour with the `RpcProvider`.

fix: repair and unify transaction retrieval error

---

__tests__/sequencerProvider.test.ts
src/provider/sequencer.ts

feat: add public sequencer fetch method

---

www/docs/API/contractFactory.md
www/docs/API/signer.md
www/docs/API/utils.md
www/docs/guides/L1message.md
www/docs/guides/connect_contract.md
www/docs/guides/define_call_message.md

Fix: typos

---

www/docusaurus.config.js

Fix typo on the landing page

---

src/provider/rpc.ts
src/provider/sequencer.ts
www/docs/API/Provider/provider.md
www/docs/API/Provider/sequencerProvider.md
www/docs/guides/L1message.md
www/docs/guides/connect_account.md
www/docs/guides/connect_contract.md
www/docs/guides/connect_network.md
www/docs/guides/create_account.md
www/docs/guides/create_contract.md
www/docs/guides/interact.md
www/versioned_docs/version-v4.17.1/API/provider.md
www/versioned_docs/version-v4.17.1/API/utils.md

...
...
- Change 1.
- ...
- Change 1.
- ...

docs: updated docs with network name and waitForTransaction

---

__tests__/utils/stark.browser.test.ts
package-lock.json
package.json
src/utils/hash.ts

Fix https://github.com/0xs34n/starknet.js/issues/527
@noble/curves": "^0.7.1"

chore: bump noble curves

---

package-lock.json
package.json
src/utils/address.ts

Closes #405 
Replace `arrayify` function from package `@ethersproject/bytes` by utils functions from the `noble-curves` package.
- Change 1.
- ...
- Change 1.
- ...

feat: replace functions @ethersproject/bytes

---

src/account/default.ts
src/account/interface.ts

fix: adjust suggested max fee response type

---

__tests__/utils/transaction.test.ts
package-lock.json
src/account/default.ts
src/provider/errors.ts
src/signer/default.ts
src/types/account.ts
src/types/lib/index.ts
src/types/signer.ts
src/utils/transaction.ts

With Cairo1, Account contracts use simpler calldata for execute. The differences are as below:
```
func __execute__(
call_array_len: felt,
call_array: CallArray*,
calldata_len: felt,
calldata: felt*
)
​
struct CallArray {
to: felt,
selector: felt,
data_offset: felt,
data_len: felt,
}
​
​
Example: 
call1 = { to: 0x8001, selector: 0x5E11, calldata: [0xCAA1, 0x1001] }
call2 = { to: 0x8002, selector: 0x5E12, calldata: [0xCAA1, 0x1000, 0x0002] }
​
0x0002 (call_array_len)
-- call_array
0x8001 (to1)
0x5E11 (selector1)
0x0000 (data offset1)
0x0002 (data len11)
0x8002 (to2)
--
0x5E12 (selector2)
0x0003 (data offset2)
0x0003 (data len12)
--
0x0005 (calldata_len)
-- (calldata)
0xCAA1
0x1001 
0xCAA1
0x1000
0x0002
​
//////////////// CAIRO 1
​
fn __execute__(calls: Array<Call>) -> Span::<felt252> {
​
} …
```

feat: support cairo1 execute calldata

---

src/types/api/index.ts

Fix contract invoke options issue

fix: optional param in contract invoke

---

__tests__/defaultProvider.test.ts
__tests__/rpcProvider.test.ts
__tests__/schema.ts
__tests__/schemas/rpc.json
package.json
src/types/api/openrpc.ts
www/docs/API/Provider/rpcProvider.md

- rel : #589 
- add tests for rpcProvider
- update getEvents docs

test: add tests for rpcProvider & update docs

---

.eslintignore
www/docs/guides/L1message.md
www/docs/guides/compiled_contracts/deployBraavos.ts
www/docs/guides/connect_account.md
www/docs/guides/connect_contract.md
www/docs/guides/connect_network.md
www/docs/guides/create_account.md
www/docs/guides/create_contract.md
www/docs/guides/define_call_message.md
www/docs/guides/estimate_fees.md
www/docs/guides/events.md
www/docs/guides/interact.md
www/docs/guides/intro.md
www/docs/guides/multiCall.md
www/docs/guides/signature.md
www/docs/guides/use_ERC20.md
www/docs/guides/what_s_starknet.js.md
www/tsconfig.json
www/versioned_docs/version-4.22.0/guides/signature.md

Solve #512 
- Complete update of guides, to includes all updates related to v5.
- Implemented in create account guide : creation of a Braavos account.
- Small fix in V4.22 doc (in signature guide).
Access to the V5 guides.
N/A 
These guides are made with the hypothesis that #633 is implemented.
For Braavos account creation, as a lot of new code is necessary, a module has been created and can be used by users. As it's outside of starknet.js code, `.eslintignore` and `tsconfig.json` have been updated accordingly.

docs: update guides to v5

---

package-lock.json
src/types/api/rpc.ts
src/types/api/sequencer.ts
src/types/index.ts
src/types/provider/response.ts
src/utils/json.ts
tsconfig.json

fix: remedy type declaration roll-up issues

---

www/docs/guides/signature.md

Update of guides : Just a small update of type for signature.
`weierstrass.SignatureType` replaced by `WeierstrassSignatureType`
N/A
N/A

docs: update type of signature

---

__tests__/contract.test.ts

...
...
- Change 1.
- ...
- Change 1.
- ...

fix: contract test status

---

src/provider/sequencer.ts

...
...
- Change 1.
- ...
- Change 1.
- ...

fix: SequencerProvider get network name

---

__tests__/rpcProvider.test.ts
__tests__/utils/merkle.test.ts
package-lock.json
package.json
src/utils/ec.ts
src/utils/hash.ts
src/utils/selector.ts
src/utils/stark.ts

Audited libraries are moved into scure namespace.

Upgrade from micro-starknet to scure-starknet

---

__tests__/cairo1v2.test.ts
src/utils/calldata/propertyOrder.ts
src/utils/encode.ts

PhilippeR26:uint256-ordering https://github.com/0xs34n/starknet.js/pull/732 @PhilippeR26 
PhilippeR26:fix-waitForTransaction https://github.com/0xs34n/starknet.js/pull/737 @PhilippeR26

Next version

---

www/docs/guides/connect_network.md

The guide is explaining how to connect to a rpc node, but only for Pathfinder.
Update is modifying pathfinder acces `(/rpc/v0.4` added), and is adding Juno and other rpc clients.
N/A
N/A

docs: update guide for rpc nodes access

---

.github/workflows/manual-tests-testnet.yml
.github/workflows/pr-push-main.yml

Hold one source of truth for Network Tests, fix CI

test: fix testnet action

---

__tests__/schemas/sequencer.json

Fix Test Json Schema for  FunctionInvocation entry_point_type

test: fix test json schema FunctionInvocation entry_point_type

---

www/docs/guides/intro.md

Old: https://docs.cairo-lang.org/hello_starknet/intro.html
New: https://docs.starknet.io/documentation/quick_start/declare_a_smart_contract/#compiling_a_smart_contract
...
...
- Change 1.
- ...
- Change 1.
- ...

docs: Update intro.md - Fix Broken Link

---

src/utils/encode.ts

This version uses TextEncoder for encoding the string into a Uint8Array, which is a modern and efficient approach.

refactor: optimization function string to array buffer

---

__tests__/fixtures.ts
__tests__/rpcProvider.test.ts
__tests__/utils/json.test.ts
src/provider/index.ts
src/provider/rpc.ts
src/types/api/rpcspec/nonspec.ts
src/types/provider/configuration.ts

* Retry until rpc is actually ready to work with txHash)
0.5.0

Update next version v5

---

src/provider/rpc.ts

fix: skip chainId eager load for RpcProvider initialization

---

src/provider/rpc.ts
src/types/api/rpcspec/components.ts
src/types/api/rpcspec/index.ts

fix https://github.com/starknet-io/starknet.js/issues/818
RPC 0.5.1 changes
0.5.1 changes

feat: rpc 0.5.1

---

CONTRIBUTING.md

Just a very small PR, to add explanation how to perform the test suite on a specific node.
...
N/A
- few lines added in CONTRIBUTING.md

docs: how to use a specific node to execute tests

---

src/signer/interface.ts

After examining the JSDoc comments for the signTransaction function, it appears to be incorrect and could potentially mislead developers.

docs: optimize JSDoc comments for signTransaction interface

---

__tests__/utils/address.test.ts
__tests__/utils/utils.test.ts
src/constants.ts
src/utils/address.ts
src/utils/hash.ts

fix: apply bound for contract address from hash calculation

---

package.json

- update noble-hashes to [1.3.3](https://github.com/paulmillr/noble-hashes/releases/tag/1.3.3)
- update noble-curves to [1.3.0](https://github.com/paulmillr/noble-curves/releases/tag/1.3.0)
- update scure-starknet to 1.0.0, which contains these upgrades

Update noble and scure deps

---

src/constants.ts
src/provider/rpc.ts
src/types/provider/configuration.ts

...
...
- Change 1.
- ...
- Change 1.
- ...

feat: sepolia

---

src/account/default.ts

...
...
- Change 1.
- ...
- Change 1.
- ...

fix: estimateFeeBulk provided version

---

www/docs/guides/events.md

A Discord user identified that the script to illustrate getEvents() is no more working.
A small update is necessary.
Guide updated
N/A

docs: update getEvents guide

---

www/versioned_docs/version-5.24.3/guides/connect_network.md

Include Version in RPC Provider URL to Avoid simulation_flags Error
Encountered an issue where initializing the RPC provider without specifying the version in the URL leads to transaction failures on the network. This results in a "missing non-optional param: simulation_flags" error, likely due to StarkNet nodes expecting the version in the URL. This requirement is not currently reflected in the documentation.
The core issue arises from the StarkNet node's expectation of a version-specific URL, which is not currently documented. Omitting the version leads to transaction failures with a "missing non-optional param: simulation_flags" error. By specifying the version in the RPC provider's URL, the correct simulation_flags parameter is utilized, ensuring compatibility with the StarkNet node's …

Include Version in RPC JUNO Provider URL to Avoid simulation_flags Error

---

__tests__/utils/stark.test.ts
src/utils/stark.ts

fix: utilize provided resourceBounds value

---

www/docs/guides/create_account.md
www/versioned_docs/version-5.14.1/guides/create_account.md
www/versioned_docs/version-5.19.5/guides/create_account.md
www/versioned_docs/version-5.24.3/guides/create_account.md

Got errors when refering the doc.
- examples in doc

fix: bug in create_account.md

---

package-lock.json
package.json

Getting a dependency upgrade which includes a TypeScript fix to fix vite builds with strict type checking configurations.
...
users building an application with vite and a tsconfig.json that includes `"isolatedModules": true` currently do not work. this dependency upgrade fixes those builds
- Change 1.
- ...

chore: update abi-wan-kanabi-v2 vo v2.1.1

---

src/utils/calldata/enum/CairoCustomEnum.ts
src/utils/calldata/enum/CairoOption.ts
src/utils/calldata/enum/CairoResult.ts
www/docusaurus.config.js
www/package-lock.json
www/package.json

Solve #875.
Add  a search tool in the top bar of the Starknet.js website.
As requested by @ivpavici , temporarily, I used my Algolia account to add the search functionality.
`docusaurus.config.js` includes the Algolia keys.
Bump versions of docusaurus and plugins (new version needs an empty `@example` line)
This functionality has been tested in my fork : https://philipper26.github.io/starknet.js/

Add search functionnality to the official website.

---

__mocks__/cairo/cairo240/string.ts
__tests__/cairo1v2_typed.test.ts

Add typed tests for the new types introduced in Cairo 2.4: `bytes31` and `ByteArray`
...
- Change 1.
- ...
- Change 1.
- ...

Test: Cairo 2.4 typed

---

__tests__/cairo1_typed.test.ts
package-lock.json
package.json
src/contract/default.ts
src/contract/interface.ts
www/versioned_docs/version-5.19.5/guides/automatic_cairo_ABI_parsing.md

Same as #933 but target `beta` branch
...
- Change 1.
- ...
- Change 1.
- ...

Chore: rename `abi-wan-kanabi` to `abi-wan-kanabi-v1`

---

__tests__/cairo1v2.test.ts
__tests__/contract.test.ts
src/utils/calldata/index.ts

feat: add provider.decodeParameters

---

src/signer/default.ts

extract a signRaw method from Signer, to make it easy to rewrite Signer

chore: refactor Signer for convenient overwriting

---

www/docs/guides/define_call_message.md
www/docs/guides/migrate.md
www/docs/guides/migrate_v4.md
www/docs/guides/signature.md
www/src/css/custom.css

Allow the documentation build to pass.

docs: repair and modify migration guide

---

src/types/api/rpcspec_0_6/components.ts

fix: rpc event

---

package-lock.json
package.json

...
...
- Change 1.
- ...
- Change 1.
- ...

chore: bump abi-wan v2

---

package-lock.json
package.json
src/utils/fetchPonyfill.ts
src/utils/json.ts

Resolves #959
...
- Change 1.
- ...
- Change 1.
- ...

Upgrade fetch-cookie

---

src/utils/starknetId.ts

We had to deploy a new version of the Starknet Id contracts on Sepolia

Update starknetid sepolia contract addresses

---

CONTRIBUTING.md
__tests__/config/constants.ts
__tests__/config/helpers/env.ts
__tests__/config/helpers/localDevnetDetector.ts
__tests__/config/jestGlobalSetup.ts

Closes #1008
The primary motivation for this PR is to improve the overall contribution guide. Furthermore, this PR introduces the `docker` approach so the contributor can easily set up the local environment.
_n.a_
When cloning the repo for the first time, you'll have a detailed guide on how to set docker and run the desired command from the tag exposed via this [link](https://hub.docker.com/r/shardlabs/starknet-devnet-rs/tags)
- Clone the repo
- run `npm run install`
- Open the docker app on your machine (or run it via terminal if it's installed via brew or some other package manager)
- Run: ```docker run -p 5050:5050 shardlabs/starknet-devnet-rs:latest```
- Run `npm run test`

docs: Add docker approach guide for dev setup 

---

src/utils/address.ts

Solve #1028 
Add documentation for 2 functions in utils/address.ts
N/A

docs: add tsdoc in utils/address.ts

---

package-lock.json
package.json

starknet-types 0.0.5 tslib fix
...
- Change 1.
- ...
- Change 1.
- ...

fix: tslib

---

src/types/api/rpcspec_0_7/components.ts
src/types/api/rpcspec_0_7/index.ts

Fix https://github.com/starknet-io/starknet.js/issues/1069
0.7.1

feat: rpc 0.7.1

---

www/src/css/custom.css

fix: styling bugfix

---

src/utils/selector.ts

- To provide developers with relevant examples for function useage
- Added JSDoc comments and examples for the getSelector function.
- Update the document to include examples.
- No changes in testing or CI/CD.

chore: Add JsDoc comments and examples for selector.ts file

---

.github/workflows/_test.yml
CONTRIBUTING.md
package.json

Solve #1089.
Produces a test coverage report.
N/A
- for a complete project coverage : `npm run test:coverage`
- example for a single file coverage : `npm run test:coverage __tests__/utils/uint256.test.ts`
The automatic test suite is reporting the coverage of the test suite. It can be easily modified if necessary here :
https://github.com/starknet-io/starknet.js/blob/37526cf6597df4e1d7675d9871369625fc5d5320/.github/workflows/_test.yml#L41

test: add coverage option

---

__tests__/utils/typedData.test.ts
package-lock.json
package.json
src/utils/typedData.ts

Implement Type Safety version of starknet-types
...
...
- Change 1.
- ...
- Change 1.
- ...

fix: types-js

---

www/docs/guides/create_account.md

Just a small correction of display in the `create account` guide.
N/A
N/A

docs: fix format pb in create account guide

---

www/docs/guides/create_contract.md

Fix invalid reference in create_contract.md

---

CONTRIBUTING.md

...
...
- Change 1.
- ...
- Change 1.
- ...

feat: dummy change

---

www/docs/guides/connect_network.md

docs: batchClient

---

www/docs/guides/create_account.md

ArgentX as upgraded its Account contract to v0.4.0, with a constructor significantly different.
Guide of account creation is updated accordingly
N/A
N/A

docs: bump ArgentX account to v0.4.0

---

www/docs/guides/migrate.md
www/docs/guides/multiCall.md
www/docs/guides/signature.md

Changes Summary
"depending of" → "depending on"
Corrected preposition for grammatical accuracy.
"require" → "requires"
Subject-verb agreement correction.
"depending if" → "depending on whether"
Improved conditional phrasing.
"is listing" → "lists"
Simplified tense for clarity

Documentation: Grammar Corrections and Consistency Updates

---

src/index.ts

fix: expose BatchClient class

---

www/docs/guides/walletAccount.md

Following a suggestion of @tabaktoni , the guide of `WalletAccount` has been updated, to add explanation about `chainId`.
N/A
N/A

docs: walletAccount - add details for chainId

---

package-lock.json
package.json

...
...
- Change 1.
- ...
- Change 1.
- ...

fix: bump types js

---

__tests__/rpcProvider.test.ts
__tests__/schemas/rpc.json

test: streamline syncing stats tests

---

www/docs/guides/connect_network.md

Just a small update of Starknet.js version in the connection guide.
Also few polishing in this guide.
N/A
N/A

docs: update starknet.js version in guide table

---

www/versioned_docs/version-5.24.3/guides/L1message.md

https://docs.starknet.io/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/ - https://docs.starknet.io/architecture-and-concepts/network-architecture/messaging-mechanism/

fix broken link

---

__tests__/utils/calldata/requestParser.test.ts
__tests__/utils/calldata/validate.test.ts

__tests__/utils/calldata/requestParser.test.ts
Custon - Custom
__tests__/utils/calldata/validate.test.ts
tupple - tuple
iz - is

chore: fix errors in code 

---

package-lock.json
package.json
src/channel/ws_0_8.ts

Updated to rpc 0.8.1
- subscription id in ws to string
- fee estimate number (this had no effect to codebase)
0.8.1

feat: update to rpc 0.8.1

---

src/utils/connect/fetch.ts

Make `fetch` compatible on all platforms, modern or not.
- Binding `fetch` to each environment's global object to avoid [issues caused during this package's bundling](https://github.com/starknet-io/starknet.js/pull/1374#discussion_r2079748387).

fix: update fetch checks

---

src/utils/events/index.ts

`myContract.parseEvents()` is working once, but not twice.
For example this code is not working:
```typescript
const txR: GetTransactionReceiptResponse = await myProvider.getTransactionReceipt(txH);
const events2 = myContract.parseEvents(txR);
const events3 = myContract.parseEvents(txR);
```
`events2` is OK, but `events3` is `[]`
Origin of the problem :
https://github.com/starknet-io/starknet.js/blob/050616221a58545d79eece7040b4abc205c220e0/src/utils/events/index.ts#L205-L210
`keys.shift()` is not local, and is executed in fact in the initial `txR`.
Bug Solved.
A deep copy is executed before use of `.shift()`:
https://github.com/PhilippeR26/starknet.js/blob/2e6343c90380a99f6c96c2030c0dd5aa8bdf8fab/src/utils/events/index.ts#L205

fix: parseEvents is not working twice

---

.github/workflows/_test.yml
.github/workflows/manual-tests-devnet.yml
.github/workflows/manual-tests-testnet.yml
.github/workflows/pr-push-dev.yml
.github/workflows/pr-push-main.yml

Changes the Testnet CI configuration from using a single node to using several combinations of different nodes, RPC specification versions, and communication protocols.

ci: expand combinations for testnet tests

---

www/docs/guides/account/paymaster.md
www/versioned_docs/version-7.6.4/guides/paymaster.md

Fix header key for paymaster api key in doc

docs: fix paymaster api key header

---

__tests__/account.test.ts
__tests__/utils/encode.test.ts
__tests__/utils/num.test.ts
__tests__/utils/utils.test.ts
src/contract/default.ts
src/deployer/default.ts
src/utils/encode.ts
src/utils/num.ts

fix: ensure cleanHex has valid output
